import '../models/roadmap.dart';

final List<Roadmap> backendRoadmap = [
  // =========================
  // Month 1
  // =========================

  // Week 1
  Roadmap(
    id: 'backend-m1-w1-d1',
    role: 'Backend',
    week: 1,
    day: 1,
    title: 'Introduction to Backend Development',
    description: 'Understand backend roles, architecture, and basics.',
  ),
  Roadmap(
    id: 'backend-m1-w1-d2',
    role: 'Backend',
    week: 1,
    day: 2,
    title: 'Version Control with Git',
    description: 'Learn Git commands, branching, and collaboration workflow.',
  ),
  Roadmap(
    id: 'backend-m1-w1-d3',
    role: 'Backend',
    week: 1,
    day: 3,
    title: 'Node.js Basics',
    description: 'Setup Node.js project, NPM, modules, and basic server.',
  ),
  Roadmap(
    id: 'backend-m1-w1-d4',
    role: 'Backend',
    week: 1,
    day: 4,
    title: 'REST API Fundamentals',
    description: 'Understand HTTP methods, status codes, and endpoints.',
  ),
  Roadmap(
    id: 'backend-m1-w1-d5',
    role: 'Backend',
    week: 1,
    day: 5,
    title: 'Express.js Basics',
    description: 'Create REST APIs with Express and handle routes.',
  ),
  Roadmap(
    id: 'backend-m1-w1-d6',
    role: 'Backend',
    week: 1,
    day: 6,
    title: 'Database Basics',
    description: 'Introduction to relational and NoSQL databases.',
  ),
  Roadmap(
    id: 'backend-m1-w1-d7',
    role: 'Backend',
    week: 1,
    day: 7,
    title: 'Project: Simple REST API',
    description: 'Build a basic REST API with Node.js and Express.',
  ),

  // Week 2
  Roadmap(
    id: 'backend-m1-w2-d1',
    role: 'Backend',
    week: 2,
    day: 1,
    title: 'Database Design',
    description: 'Learn schema design and normalization for relational DB.',
  ),
  Roadmap(
    id: 'backend-m1-w2-d2',
    role: 'Backend',
    week: 2,
    day: 2,
    title: 'CRUD Operations',
    description: 'Implement Create, Read, Update, Delete in backend APIs.',
  ),
  Roadmap(
    id: 'backend-m1-w2-d3',
    role: 'Backend',
    week: 2,
    day: 3,
    title: 'Authentication & Authorization',
    description: 'Learn JWT, sessions, and role-based access control.',
  ),
  Roadmap(
    id: 'backend-m1-w2-d4',
    role: 'Backend',
    week: 2,
    day: 4,
    title: 'Error Handling & Middleware',
    description: 'Use middleware and structured error handling in Express.',
  ),
  Roadmap(
    id: 'backend-m1-w2-d5',
    role: 'Backend',
    week: 2,
    day: 5,
    title: 'Environment Variables & Config',
    description: 'Manage configs using .env and separate settings.',
  ),
  Roadmap(
    id: 'backend-m1-w2-d6',
    role: 'Backend',
    week: 2,
    day: 6,
    title: 'Postman & API Testing',
    description: 'Test APIs and automate with Postman collections.',
  ),
  Roadmap(
    id: 'backend-m1-w2-d7',
    role: 'Backend',
    week: 2,
    day: 7,
    title: 'Project: User Management API',
    description: 'Build a user management API with CRUD and auth.',
  ),

  // Week 3
  Roadmap(
    id: 'backend-m1-w3-d1',
    role: 'Backend',
    week: 3,
    day: 1,
    title: 'Relational Database Advanced',
    description: 'Joins, indexes, constraints, and transactions.',
  ),
  Roadmap(
    id: 'backend-m1-w3-d2',
    role: 'Backend',
    week: 3,
    day: 2,
    title: 'NoSQL Database Basics',
    description: 'Learn MongoDB collections, documents, and queries.',
  ),
  Roadmap(
    id: 'backend-m1-w3-d3',
    role: 'Backend',
    week: 3,
    day: 3,
    title: 'Connecting Backend to Database',
    description: 'Integrate SQL/NoSQL DB with Node.js backend.',
  ),
  Roadmap(
    id: 'backend-m1-w3-d4',
    role: 'Backend',
    week: 3,
    day: 4,
    title: 'Data Validation & Sanitization',
    description: 'Validate input data and prevent injection attacks.',
  ),
  Roadmap(
    id: 'backend-m1-w3-d5',
    role: 'Backend',
    week: 3,
    day: 5,
    title: 'API Pagination & Filtering',
    description: 'Handle large datasets with pagination and filtering.',
  ),
  Roadmap(
    id: 'backend-m1-w3-d6',
    role: 'Backend',
    week: 3,
    day: 6,
    title: 'Logging & Debugging',
    description: 'Implement logging for development and production.',
  ),
  Roadmap(
    id: 'backend-m1-w3-d7',
    role: 'Backend',
    week: 3,
    day: 7,
    title: 'Project: Blog API',
    description: 'Build a full-featured blog API with posts, comments, and users.',
  ),

  // Week 4
  Roadmap(
    id: 'backend-m1-w4-d1',
    role: 'Backend',
    week: 4,
    day: 1,
    title: 'Advanced Authentication',
    description: 'Implement OAuth2 and role-based access control.',
  ),
  Roadmap(
    id: 'backend-m1-w4-d2',
    role: 'Backend',
    week: 4,
    day: 2,
    title: 'File Upload & Storage',
    description: 'Learn to handle file uploads and storage using AWS S3 or Firebase Storage.',
  ),
  Roadmap(
    id: 'backend-m1-w4-d3',
    role: 'Backend',
    week: 4,
    day: 3,
    title: 'Background Jobs',
    description: 'Learn queues, cron jobs, and scheduled tasks.',
  ),
  Roadmap(
    id: 'backend-m1-w4-d4',
    role: 'Backend',
    week: 4,
    day: 4,
    title: 'API Rate Limiting & Throttling',
    description: 'Protect your APIs against abuse with rate limits.',
  ),
  Roadmap(
    id: 'backend-m1-w4-d5',
    role: 'Backend',
    week: 4,
    day: 5,
    title: 'API Versioning & Documentation',
    description: 'Learn to version APIs and maintain proper documentation.',
  ),
  Roadmap(
    id: 'backend-m1-w4-d6',
    role: 'Backend',
    week: 4,
    day: 6,
    title: 'Unit Testing & Mocking',
    description: 'Write unit tests for controllers, services, and models.',
  ),
  Roadmap(
    id: 'backend-m1-w4-d7',
    role: 'Backend',
    week: 4,
    day: 7,
    title: 'Project: Authentication & File Upload API',
    description: 'Build a small project implementing auth, file upload, and role-based permissions.',
  ),

  // =========================
  // Month 2
  // =========================

  // Week 5
  Roadmap(
    id: 'backend-m2-w5-d1',
    role: 'Backend',
    week: 5,
    day: 1,
    title: 'Introduction to GraphQL',
    description: 'Learn GraphQL queries, mutations, and schema design.',
  ),
  Roadmap(
    id: 'backend-m2-w5-d2',
    role: 'Backend',
    week: 5,
    day: 2,
    title: 'GraphQL with Node.js',
    description: 'Implement GraphQL endpoints using Apollo Server or Express.',
  ),
  Roadmap(
    id: 'backend-m2-w5-d3',
    role: 'Backend',
    week: 5,
    day: 3,
    title: 'Subscriptions & Real-time APIs',
    description: 'Implement real-time updates using WebSockets or GraphQL subscriptions.',
  ),
  Roadmap(
    id: 'backend-m2-w5-d4',
    role: 'Backend',
    week: 5,
    day: 4,
    title: 'API Security Best Practices',
    description: 'Learn input validation, CORS, CSRF, and XSS protection.',
  ),
  Roadmap(
    id: 'backend-m2-w5-d5',
    role: 'Backend',
    week: 5,
    day: 5,
    title: 'API Performance & Monitoring',
    description: 'Use monitoring tools and performance optimization techniques.',
  ),
  Roadmap(
    id: 'backend-m2-w5-d6',
    role: 'Backend',
    week: 5,
    day: 6,
    title: 'Logging & Error Tracking',
    description: 'Integrate logging libraries and error tracking tools.',
  ),
  Roadmap(
    id: 'backend-m2-w5-d7',
    role: 'Backend',
    week: 5,
    day: 7,
    title: 'Project: GraphQL API',
    description: 'Build a GraphQL API with queries, mutations, and subscriptions for a mini app.',
  ),

  // Week 6
  Roadmap(
    id: 'backend-m2-w6-d1',
    role: 'Backend',
    week: 6,
    day: 1,
    title: 'Microservices Architecture',
    description: 'Understand microservices and service separation.',
  ),
  Roadmap(
    id: 'backend-m2-w6-d2',
    role: 'Backend',
    week: 6,
    day: 2,
    title: 'API Gateway & Routing',
    description: 'Implement API gateways to route requests.',
  ),
  Roadmap(
    id: 'backend-m2-w6-d3',
    role: 'Backend',
    week: 6,
    day: 3,
    title: 'Service Communication',
    description: 'Learn REST, gRPC, and message queues for services.',
  ),
  Roadmap(
    id: 'backend-m2-w6-d4',
    role: 'Backend',
    week: 6,
    day: 4,
    title: 'Database per Service',
    description: 'Design DB schema for each microservice.',
  ),
  Roadmap(
    id: 'backend-m2-w6-d5',
    role: 'Backend',
    week: 6,
    day: 5,
    title: 'Logging in Microservices',
    description: 'Centralized logging with tools like ELK.',
  ),
  Roadmap(
    id: 'backend-m2-w6-d6',
    role: 'Backend',
    week: 6,
    day: 6,
    title: 'Monitoring & Alerts',
    description: 'Set up monitoring dashboards and alerts.',
  ),
  Roadmap(
    id: 'backend-m2-w6-d7',
    role: 'Backend',
    week: 6,
    day: 7,
    title: 'Project: Microservice Authentication Service',
    description: 'Build a standalone auth microservice with REST API.',
  ),

  // Week 7
  Roadmap(
    id: 'backend-m2-w7-d1',
    role: 'Backend',
    week: 7,
    day: 1,
    title: 'Docker Basics',
    description: 'Learn containerization with Docker.',
  ),
  Roadmap(
    id: 'backend-m2-w7-d2',
    role: 'Backend',
    week: 7,
    day: 2,
    title: 'Docker Compose',
    description: 'Run multiple services using Docker Compose.',
  ),
  Roadmap(
    id: 'backend-m2-w7-d3',
    role: 'Backend',
    week: 7,
    day: 3,
    title: 'CI/CD Introduction',
    description: 'Understand continuous integration and deployment.',
  ),
  Roadmap(
    id: 'backend-m2-w7-d4',
    role: 'Backend',
    week: 7,
    day: 4,
    title: 'Automated Testing',
    description: 'Run unit and integration tests in CI pipeline.',
  ),
  Roadmap(
    id: 'backend-m2-w7-d5',
    role: 'Backend',
    week: 7,
    day: 5,
    title: 'Deploying to Cloud',
    description: 'Deploy backend services to AWS, GCP, or Heroku.',
  ),
  Roadmap(
    id: 'backend-m2-w7-d6',
    role: 'Backend',
    week: 7,
    day: 6,
    title: 'Secrets Management',
    description: 'Manage API keys and secrets securely.',
  ),
  Roadmap(
    id: 'backend-m2-w7-d7',
    role: 'Backend',
    week: 7,
    day: 7,
    title: 'Project: Dockerized Microservices',
    description: 'Containerize microservices and run with Docker Compose.',
  ),

// Week 8
  Roadmap(
    id: 'backend-m2-w8-d1',
    role: 'Backend',
    week: 8,
    day: 1,
    title: 'Message Queues Introduction',
    description: 'Learn RabbitMQ or Kafka basics.',
  ),
  Roadmap(
    id: 'backend-m2-w8-d2',
    role: 'Backend',
    week: 8,
    day: 2,
    title: 'Publisher & Consumer',
    description: 'Implement producer and consumer services.',
  ),
  Roadmap(
    id: 'backend-m2-w8-d3',
    role: 'Backend',
    week: 8,
    day: 3,
    title: 'Event-driven Architecture',
    description: 'Learn events, pub/sub, and asynchronous communication.',
  ),
  Roadmap(
    id: 'backend-m2-w8-d4',
    role: 'Backend',
    week: 8,
    day: 4,
    title: 'Retry & Dead Letter Queues',
    description: 'Handle failed messages with retry and dead-letter.',
  ),
  Roadmap(
    id: 'backend-m2-w8-d5',
    role: 'Backend',
    week: 8,
    day: 5,
    title: 'Monitoring Queues',
    description: 'Monitor queues for message lag and errors.',
  ),
  Roadmap(
    id: 'backend-m2-w8-d6',
    role: 'Backend',
    week: 8,
    day: 6,
    title: 'Security in Message Queues',
    description: 'Encrypt and secure messages between services.',
  ),
  Roadmap(
    id: 'backend-m2-w8-d7',
    role: 'Backend',
    week: 8,
    day: 7,
    title: 'Project: Event-driven Microservice',
    description: 'Build a microservice communicating via message queues.',
  ),
  
  // =========================
  // Month 3
  // =========================

  // Week 9
  Roadmap(
    id: 'backend-m3-w9-d1',
    role: 'Backend',
    week: 9,
    day: 1,
    title: 'Caching Strategies',
    description: 'Learn caching with Redis or in-memory solutions.',
  ),
  Roadmap(
    id: 'backend-m3-w9-d2',
    role: 'Backend',
    week: 9,
    day: 2,
    title: 'API Caching',
    description: 'Cache API responses to improve performance.',
  ),
  Roadmap(
    id: 'backend-m3-w9-d3',
    role: 'Backend',
    week: 9,
    day: 3,
    title: 'Database Indexing',
    description: 'Optimize queries with proper indexing.',
  ),
  Roadmap(
    id: 'backend-m3-w9-d4',
    role: 'Backend',
    week: 9,
    day: 4,
    title: 'Monitoring & Metrics',
    description: 'Collect metrics for service health and performance.',
  ),
  Roadmap(
    id: 'backend-m3-w9-d5',
    role: 'Backend',
    week: 9,
    day: 5,
    title: 'Scaling Strategies',
    description: 'Horizontal and vertical scaling techniques.',
  ),
  Roadmap(
    id: 'backend-m3-w9-d6',
    role: 'Backend',
    week: 9,
    day: 6,
    title: 'Database Replication & Backup',
    description: 'Setup DB replication and backup strategies.',
  ),
  Roadmap(
    id: 'backend-m3-w9-d7',
    role: 'Backend',
    week: 9,
    day: 7,
    title: 'Project: Caching & Scaling',
    description: 'Build a scalable backend with caching and replication.',
  ),

  // Week 10
  Roadmap(
    id: 'backend-m3-w10-d1',
    role: 'Backend',
    week: 10,
    day: 1,
    title: 'Authentication Refresh Tokens',
    description: 'Implement refresh tokens and token rotation.',
  ),
  Roadmap(
    id: 'backend-m3-w10-d2',
    role: 'Backend',
    week: 10,
    day: 2,
    title: 'Advanced GraphQL Features',
    description: 'Learn directives, fragments, and batching.',
  ),
  Roadmap(
    id: 'backend-m3-w10-d3',
    role: 'Backend',
    week: 10,
    day: 3,
    title: 'WebSockets & Real-time Data',
    description: 'Implement real-time notifications and updates.',
  ),
  Roadmap(
    id: 'backend-m3-w10-d4',
    role: 'Backend',
    week: 10,
    day: 4,
    title: 'Rate Limiting & Security Enhancements',
    description: 'Apply rate limits, input sanitization, and logging.',
  ),
  Roadmap(
    id: 'backend-m3-w10-d5',
    role: 'Backend',
    week: 10,
    day: 5,
    title: 'Testing GraphQL & REST APIs',
    description: 'End-to-end tests for all APIs.',
  ),
  Roadmap(
    id: 'backend-m3-w10-d6',
    role: 'Backend',
    week: 10,
    day: 6,
    title: 'API Documentation Automation',
    description: 'Generate documentation automatically with tools like Swagger.',
  ),
  Roadmap(
    id: 'backend-m3-w10-d7',
    role: 'Backend',
    week: 10,
    day: 7,
    title: 'Project: Real-time Chat Backend',
    description: 'Build a chat backend with GraphQL subscriptions and WebSockets.',
  ),

  // Week 11
  Roadmap(
    id: 'backend-m3-w11-d1',
    role: 'Backend',
    week: 11,
    day: 1,
    title: 'Security Best Practices',
    description: 'Learn OWASP guidelines and security patterns.',
  ),
  Roadmap(
    id: 'backend-m3-w11-d2',
    role: 'Backend',
    week: 11,
    day: 2,
    title: 'Authentication Microservice',
    description: 'Separate authentication into its own microservice.',
  ),
  Roadmap(
    id: 'backend-m3-w11-d3',
    role: 'Backend',
    week: 11,
    day: 3,
    title: 'Logging & Tracing Microservices',
    description: 'Implement centralized logging and tracing.',
  ),
  Roadmap(
    id: 'backend-m3-w11-d4',
    role: 'Backend',
    week: 11,
    day: 4,
    title: 'Rate Limits in Microservices',
    description: 'Apply rate limiting to distributed services.',
  ),
  Roadmap(
    id: 'backend-m3-w11-d5',
    role: 'Backend',
    week: 11,
    day: 5,
    title: 'Performance Optimization',
    description: 'Profile and optimize backend services.',
  ),
  Roadmap(
    id: 'backend-m3-w11-d6',
    role: 'Backend',
    week: 11,
    day: 6,
    title: 'Deploying Multi-service Backend',
    description: 'Deploy all microservices with CI/CD.',
  ),
  Roadmap(
    id: 'backend-m3-w11-d7',
    role: 'Backend',
    week: 11,
    day: 7,
    title: 'Project: Complete Microservice App',
    description: 'Build a fully functional microservice application.',
  ),

  // Week 12
  Roadmap(
    id: 'backend-m3-w12-d1',
    role: 'Backend',
    week: 12,
    day: 1,
    title: 'Final Testing & QA',
    description: 'Perform full testing across services.',
  ),
  Roadmap(
    id: 'backend-m3-w12-d2',
    role: 'Backend',
    week: 12,
    day: 2,
    title: 'Deployment to Production',
    description: 'Deploy services to production environment.',
  ),
  Roadmap(
    id: 'backend-m3-w12-d3',
    role: 'Backend',
    week: 12,
    day: 3,
    title: 'Monitoring & Analytics',
    description: 'Integrate monitoring dashboards and analytics tools.',
  ),
  Roadmap(
    id: 'backend-m3-w12-d4',
    role: 'Backend',
    week: 12,
    day: 4,
    title: 'Documentation & Handover',
    description: 'Document the system and prepare handover notes.',
  ),
  Roadmap(
    id: 'backend-m3-w12-d5',
    role: 'Backend',
    week: 12,
    day: 5,
    title: 'Performance Review',
    description: 'Analyze backend performance and improvements.',
  ),
  Roadmap(
    id: 'backend-m3-w12-d6',
    role: 'Backend',
    week: 12,
    day: 6,
    title: 'Refactoring & Optimization',
    description: 'Refactor code for readability and efficiency.',
  ),
  Roadmap(
    id: 'backend-m3-w12-d7',
    role: 'Backend',
    week: 12,
    day: 7,
    title: 'Project: Final Capstone Backend',
    description: 'Complete a final backend project integrating all concepts.',
  ),
];
