import '../models/roadmap.dart';

final List<Roadmap> frontendRoadmap = [
  // =========================
  // Month 1
  // =========================

  // Week 1
  Roadmap(
    id: 'frontend-m1-w1-d1',
    role: 'Frontend',
    week: 1,
    day: 1,
    title: 'Introduction to Frontend Development',
    description: 'Learn frontend roles, workflow, and core concepts.',
  ),
  Roadmap(
    id: 'frontend-m1-w1-d2',
    role: 'Frontend',
    week: 1,
    day: 2,
    title: 'HTML Basics',
    description: 'Structure web pages with semantic HTML tags.',
  ),
  Roadmap(
    id: 'frontend-m1-w1-d3',
    role: 'Frontend',
    week: 1,
    day: 3,
    title: 'CSS Fundamentals',
    description: 'Style pages with CSS, selectors, and basic layouts.',
  ),
  Roadmap(
    id: 'frontend-m1-w1-d4',
    role: 'Frontend',
    week: 1,
    day: 4,
    title: 'JavaScript Basics',
    description: 'Learn JS syntax, variables, functions, and DOM manipulation.',
  ),
  Roadmap(
    id: 'frontend-m1-w1-d5',
    role: 'Frontend',
    week: 1,
    day: 5,
    title: 'Responsive Design',
    description: 'Implement responsive layouts with media queries.',
  ),
  Roadmap(
    id: 'frontend-m1-w1-d6',
    role: 'Frontend',
    week: 1,
    day: 6,
    title: 'Browser DevTools',
    description: 'Inspect, debug, and troubleshoot using DevTools.',
  ),
  Roadmap(
    id: 'frontend-m1-w1-d7',
    role: 'Frontend',
    week: 1,
    day: 7,
    title: 'Project: Personal Landing Page',
    description: 'Build a responsive landing page using HTML, CSS, and JS.',
  ),

  // Week 2
  Roadmap(
    id: 'frontend-m1-w2-d1',
    role: 'Frontend',
    week: 2,
    day: 1,
    title: 'Advanced CSS',
    description: 'Learn Flexbox, Grid, and animations.',
  ),
  Roadmap(
    id: 'frontend-m1-w2-d2',
    role: 'Frontend',
    week: 2,
    day: 2,
    title: 'JavaScript DOM & Events',
    description: 'Manipulate DOM dynamically and handle events.',
  ),
  Roadmap(
    id: 'frontend-m1-w2-d3',
    role: 'Frontend',
    week: 2,
    day: 3,
    title: 'ES6+ Features',
    description: 'Learn modern JS features like arrow functions, promises, and classes.',
  ),
  Roadmap(
    id: 'frontend-m1-w2-d4',
    role: 'Frontend',
    week: 2,
    day: 4,
    title: 'Version Control with Git',
    description: 'Use Git for collaboration and version tracking.',
  ),
  Roadmap(
    id: 'frontend-m1-w2-d5',
    role: 'Frontend',
    week: 2,
    day: 5,
    title: 'Forms & Validation',
    description: 'Create forms and validate user input.',
  ),
  Roadmap(
    id: 'frontend-m1-w2-d6',
    role: 'Frontend',
    week: 2,
    day: 6,
    title: 'CSS Preprocessors',
    description: 'Learn SASS or LESS for modular CSS.',
  ),
  Roadmap(
    id: 'frontend-m1-w2-d7',
    role: 'Frontend',
    week: 2,
    day: 7,
    title: 'Project: Portfolio Page',
    description: 'Build a multi-section portfolio website with HTML, CSS, and JS.',
  ),

  // Week 3
  Roadmap(
    id: 'frontend-m1-w3-d1',
    role: 'Frontend',
    week: 3,
    day: 1,
    title: 'Introduction to React',
    description: 'Understand components, props, and state.',
  ),
  Roadmap(
    id: 'frontend-m1-w3-d2',
    role: 'Frontend',
    week: 3,
    day: 2,
    title: 'JSX & Component Hierarchy',
    description: 'Learn JSX syntax and parent-child components.',
  ),
  Roadmap(
    id: 'frontend-m1-w3-d3',
    role: 'Frontend',
    week: 3,
    day: 3,
    title: 'Handling Events in React',
    description: 'Manage user interactions with event handlers.',
  ),
  Roadmap(
    id: 'frontend-m1-w3-d4',
    role: 'Frontend',
    week: 3,
    day: 4,
    title: 'React State & Lifecycle',
    description: 'Manage component state and lifecycle methods.',
  ),
  Roadmap(
    id: 'frontend-m1-w3-d5',
    role: 'Frontend',
    week: 3,
    day: 5,
    title: 'React Forms & Validation',
    description: 'Create and validate forms in React.',
  ),
  Roadmap(
    id: 'frontend-m1-w3-d6',
    role: 'Frontend',
    week: 3,
    day: 6,
    title: 'Routing with React Router',
    description: 'Navigate between pages with React Router.',
  ),
  Roadmap(
    id: 'frontend-m1-w3-d7',
    role: 'Frontend',
    week: 3,
    day: 7,
    title: 'Project: React Portfolio',
    description: 'Convert portfolio page into a React single-page application.',
  ),

  // Week 4
  Roadmap(
    id: 'frontend-m1-w4-d1',
    role: 'Frontend',
    week: 4,
    day: 1,
    title: 'State Management Basics',
    description: 'Learn context API and simple global state.',
  ),
  Roadmap(
    id: 'frontend-m1-w4-d2',
    role: 'Frontend',
    week: 4,
    day: 2,
    title: 'Advanced State Management',
    description: 'Introduction to Redux or Zustand.',
  ),
  Roadmap(
    id: 'frontend-m1-w4-d3',
    role: 'Frontend',
    week: 4,
    day: 3,
    title: 'Fetching Data from API',
    description: 'Use fetch or axios to get data from REST APIs.',
  ),
  Roadmap(
    id: 'frontend-m1-w4-d4',
    role: 'Frontend',
    week: 4,
    day: 4,
    title: 'Async Programming in JS',
    description: 'Learn async/await and promises for API calls.',
  ),
  Roadmap(
    id: 'frontend-m1-w4-d5',
    role: 'Frontend',
    week: 4,
    day: 5,
    title: 'Error Handling & Debugging',
    description: 'Handle errors gracefully and debug effectively.',
  ),
  Roadmap(
    id: 'frontend-m1-w4-d6',
    role: 'Frontend',
    week: 4,
    day: 6,
    title: 'CSS Frameworks',
    description: 'Learn TailwindCSS or Bootstrap for faster styling.',
  ),
  Roadmap(
    id: 'frontend-m1-w4-d7',
    role: 'Frontend',
    week: 4,
    day: 7,
    title: 'Project: React Blog App',
    description: 'Build a blog SPA fetching posts from an API.',
  ),

  // =========================
  // Month 2 (Week 5–8)
  // =========================

  // Week 5
  Roadmap(
    id: 'frontend-m2-w5-d1',
    role: 'Frontend',
    week: 5,
    day: 1,
    title: 'React Hooks Overview',
    description: 'Learn useState, useEffect, and custom hooks.',
  ),
  Roadmap(
    id: 'frontend-m2-w5-d2',
    role: 'Frontend',
    week: 5,
    day: 2,
    title: 'Custom Hooks',
    description: 'Create reusable logic with custom hooks.',
  ),
  Roadmap(
    id: 'frontend-m2-w5-d3',
    role: 'Frontend',
    week: 5,
    day: 3,
    title: 'React Context API',
    description: 'Manage global state using context API.',
  ),
  Roadmap(
    id: 'frontend-m2-w5-d4',
    role: 'Frontend',
    week: 5,
    day: 4,
    title: 'React Router Advanced',
    description: 'Nested routes, dynamic routes, and redirects.',
  ),
  Roadmap(
    id: 'frontend-m2-w5-d5',
    role: 'Frontend',
    week: 5,
    day: 5,
    title: 'Handling Forms with Formik',
    description: 'Use Formik for form management and validation.',
  ),
  Roadmap(
    id: 'frontend-m2-w5-d6',
    role: 'Frontend',
    week: 5,
    day: 6,
    title: 'React Performance Optimization',
    description: 'Use memo, lazy loading, and code splitting.',
  ),
  Roadmap(
    id: 'frontend-m2-w5-d7',
    role: 'Frontend',
    week: 5,
    day: 7,
    title: 'Project: React E-commerce Page',
    description: 'Build a product listing page with React and API data.',
  ),

  // Week 6
  Roadmap(
    id: 'frontend-m2-w6-d1',
    role: 'Frontend',
    week: 6,
    day: 1,
    title: 'Introduction to TypeScript',
    description: 'Learn TypeScript basics and benefits for React.',
  ),
  Roadmap(
    id: 'frontend-m2-w6-d2',
    role: 'Frontend',
    week: 6,
    day: 2,
    title: 'TypeScript with React',
    description: 'Use TypeScript for type safety in React components.',
  ),
  Roadmap(
    id: 'frontend-m2-w6-d3',
    role: 'Frontend',
    week: 6,
    day: 3,
    title: 'Advanced TypeScript Types',
    description: 'Learn interfaces, generics, and utility types.',
  ),
  Roadmap(
    id: 'frontend-m2-w6-d4',
    role: 'Frontend',
    week: 6,
    day: 4,
    title: 'State Management with Redux',
    description: 'Implement Redux for complex state management.',
  ),
  Roadmap(
    id: 'frontend-m2-w6-d5',
    role: 'Frontend',
    week: 6,
    day: 5,
    title: 'Redux Thunk & Middleware',
    description: 'Handle async actions and side effects in Redux.',
  ),
  Roadmap(
    id: 'frontend-m2-w6-d6',
    role: 'Frontend',
    week: 6,
    day: 6,
    title: 'Testing React Components',
    description: 'Use Jest and React Testing Library for unit tests.',
  ),
  Roadmap(
    id: 'frontend-m2-w6-d7',
    role: 'Frontend',
    week: 6,
    day: 7,
    title: 'Project: TypeScript React App',
    description: 'Build a React app using TypeScript and Redux.',
  ),

  // Week 7
  Roadmap(
    id: 'frontend-m2-w7-d1',
    role: 'Frontend',
    week: 7,
    day: 1,
    title: 'Responsive Design with TailwindCSS',
    description: 'Build responsive layouts using TailwindCSS utility classes.',
  ),
  Roadmap(
    id: 'frontend-m2-w7-d2',
    role: 'Frontend',
    week: 7,
    day: 2,
    title: 'Advanced React Patterns',
    description: 'Learn higher-order components, render props, and compound components.',
  ),
  Roadmap(
    id: 'frontend-m2-w7-d3',
    role: 'Frontend',
    week: 7,
    day: 3,
    title: 'State Management with MobX',
    description: 'Use MobX for reactive state management in React.',
  ),
  Roadmap(
    id: 'frontend-m2-w7-d4',
    role: 'Frontend',
    week: 7,
    day: 4,
    title: 'GraphQL Basics',
    description: 'Learn GraphQL queries, mutations, and schema design.',
  ),
  Roadmap(
    id: 'frontend-m2-w7-d5',
    role: 'Frontend',
    week: 7,
    day: 5,
    title: 'Apollo Client with React',
    description: 'Integrate Apollo Client for GraphQL data fetching.',
  ),
  Roadmap(
    id: 'frontend-m2-w7-d6',
    role: 'Frontend',
    week: 7,
    day: 6,
    title: 'Authentication in React Apps',
    description: 'Implement authentication flows using JWT or OAuth.',
  ),
  Roadmap(
    id: 'frontend-m2-w7-d7',
    role: 'Frontend',
    week: 7,
    day: 7,
    title: 'Project: GraphQL React App',
    description: 'Build a React app consuming a GraphQL API with authentication.',
  ),

 // Week 8
  Roadmap(
    id: 'frontend-m2-w8-d1',
    role: 'Frontend',
    week: 8,
    day: 1,
    title: 'Finalizing Responsive Layouts',
    description: 'Ensure all components work seamlessly on multiple screen sizes.',
  ),
  Roadmap(
    id: 'frontend-m2-w8-d2',
    role: 'Frontend',
    week: 8,
    day: 2,
    title: 'Finalizing React Forms',
    description: 'Complete all forms with validation and proper error handling.',
  ),
  Roadmap(
    id: 'frontend-m2-w8-d3',
    role: 'Frontend',
    week: 8,
    day: 3,
    title: 'API Data Integration',
    description: 'Connect remaining APIs to fetch dynamic data for components.',
  ),
  Roadmap(
    id: 'frontend-m2-w8-d4',
    role: 'Frontend',
    week: 8,
    day: 4,
    title: 'Authentication Flows',
    description: 'Ensure login, registration, and auth flows are secure and functional.',
  ),
  Roadmap(
    id: 'frontend-m2-w8-d5',
    role: 'Frontend',
    week: 8,
    day: 5,
    title: 'UI Bug Fixes & Improvements',
    description: 'Fix all minor UI bugs and polish the interface for consistency.',
  ),
  Roadmap(
    id: 'frontend-m2-w8-d6',
    role: 'Frontend',
    week: 8,
    day: 6,
    title: 'Final Testing & Debugging',
    description: 'Test all components, fix final bugs, and ensure everything works as expected.',
  ),
  Roadmap(
    id: 'frontend-m2-w8-d7',
    role: 'Frontend',
    week: 8,
    day: 7,
    title: 'Week 8 Project: Build a Mini Dashboard',
    description: 'Create a mini dashboard implementing everything learned this week. Submit for review.',
  ),


  // =========================
  // Month 3 (Week 9–12)
  // =========================

  // Week 9
  Roadmap(
    id: 'frontend-m3-w9-d1',
    role: 'Frontend',
    week: 9,
    day: 1,
    title: 'Unit Testing in React',
    description: 'Learn to write unit tests for components with Jest.',
  ),
  Roadmap(
    id: 'frontend-m3-w9-d2',
    role: 'Frontend',
    week: 9,
    day: 2,
    title: 'Integration Testing',
    description: 'Test component interactions and API integrations.',
  ),
  Roadmap(
    id: 'frontend-m3-w9-d3',
    role: 'Frontend',
    week: 9,
    day: 3,
    title: 'End-to-End Testing',
    description: 'Use tools like Cypress to test the full app flow.',
  ),
  Roadmap(
    id: 'frontend-m3-w9-d4',
    role: 'Frontend',
    week: 9,
    day: 4,
    title: 'CI/CD Basics',
    description: 'Understand continuous integration and deployment workflows.',
  ),
  Roadmap(
    id: 'frontend-m3-w9-d5',
    role: 'Frontend',
    week: 9,
    day: 5,
    title: 'Deployment to Vercel/Netlify',
    description: 'Deploy React apps using popular hosting platforms.',
  ),
  Roadmap(
    id: 'frontend-m3-w9-d6',
    role: 'Frontend',
    week: 9,
    day: 6,
    title: 'Performance Monitoring',
    description: 'Learn tools to monitor performance and improve UX.',
  ),
  Roadmap(
    id: 'frontend-m3-w9-d7',
    role: 'Frontend',
    week: 9,
    day: 7,
    title: 'Project: Todo App with Testing',
    description: 'Build a fully tested React Todo app with deployment.',
  ),

  // Week 10
  Roadmap(
    id: 'frontend-m3-w10-d1',
    role: 'Frontend',
    week: 10,
    day: 1,
    title: 'Advanced CSS Animations',
    description: 'Create smooth and interactive animations for UI.',
  ),
  Roadmap(
    id: 'frontend-m3-w10-d2',
    role: 'Frontend',
    week: 10,
    day: 2,
    title: 'Accessibility Basics',
    description: 'Make apps accessible for all users (a11y).',
  ),
  Roadmap(
    id: 'frontend-m3-w10-d3',
    role: 'Frontend',
    week: 10,
    day: 3,
    title: 'SEO for React Apps',
    description: 'Optimize React apps for search engines.',
  ),
  Roadmap(
    id: 'frontend-m3-w10-d4',
    role: 'Frontend',
    week: 10,
    day: 4,
    title: 'Advanced State Management',
    description: 'Use Redux Toolkit or Zustand for complex apps.',
  ),
  Roadmap(
    id: 'frontend-m3-w10-d5',
    role: 'Frontend',
    week: 10,
    day: 5,
    title: 'React Performance Optimization',
    description: 'Profile and optimize React apps for speed and size.',
  ),
  Roadmap(
    id: 'frontend-m3-w10-d6',
    role: 'Frontend',
    week: 10,
    day: 6,
    title: 'API Integration with GraphQL',
    description: 'Use Apollo Client to fetch and mutate data.',
  ),
  Roadmap(
    id: 'frontend-m3-w10-d7',
    role: 'Frontend',
    week: 10,
    day: 7,
    title: 'Project: Advanced React Dashboard',
    description: 'Build a dashboard using Redux and GraphQL APIs.',
  ),

  // Week 11
  Roadmap(
    id: 'frontend-m3-w11-d1',
    role: 'Frontend',
    week: 11,
    day: 1,
    title: 'Progressive Web Apps',
    description: 'Convert React apps into PWAs for offline support.',
  ),
  Roadmap(
    id: 'frontend-m3-w11-d2',
    role: 'Frontend',
    week: 11,
    day: 2,
    title: 'React Hooks Deep Dive',
    description: 'Advanced hooks like useReducer, useCallback, useMemo.',
  ),
  Roadmap(
    id: 'frontend-m3-w11-d3',
    role: 'Frontend',
    week: 11,
    day: 3,
    title: 'Component Libraries',
    description: 'Use Material UI, Chakra UI, or Ant Design components.',
  ),
  Roadmap(
    id: 'frontend-m3-w11-d4',
    role: 'Frontend',
    week: 11,
    day: 4,
    title: 'Custom Component Design',
    description: 'Create reusable UI components for scalability.',
  ),
  Roadmap(
    id: 'frontend-m3-w11-d5',
    role: 'Frontend',
    week: 11,
    day: 5,
    title: 'State Management Advanced Patterns',
    description: 'Learn selectors, middleware, and advanced store setup.',
  ),
  Roadmap(
    id: 'frontend-m3-w11-d6',
    role: 'Frontend',
    week: 11,
    day: 6,
    title: 'Unit & Integration Tests',
    description: 'Improve code quality using automated tests.',
  ),
  Roadmap(
    id: 'frontend-m3-w11-d7',
    role: 'Frontend',
    week: 11,
    day: 7,
    title: 'Project: SaaS Admin Panel',
    description: 'Build a full-featured React admin panel for SaaS app.',
  ),

  // Week 12
  Roadmap(
    id: 'frontend-m3-w12-d1',
    role: 'Frontend',
    week: 12,
    day: 1,
    title: 'Final Capstone Overview',
    description: 'Plan final project combining all learned skills.',
  ),
  Roadmap(
    id: 'frontend-m3-w12-d2',
    role: 'Frontend',
    week: 12,
    day: 2,
    title: 'Set up Backend Integration',
    description: 'Connect frontend app with backend APIs.',
  ),
  Roadmap(
    id: 'frontend-m3-w12-d3',
    role: 'Frontend',
    week: 12,
    day: 3,
    title: 'State Management Final',
    description: 'Implement state management for final project.',
  ),
  Roadmap(
    id: 'frontend-m3-w12-d4',
    role: 'Frontend',
    week: 12,
    day: 4,
    title: 'UI Polishing',
    description: 'Enhance UI, responsive design, and animations.',
  ),
  Roadmap(
    id: 'frontend-m3-w12-d5',
    role: 'Frontend',
    week: 12,
    day: 5,
    title: 'Testing & Debugging',
    description: 'Ensure final project is bug-free and performant.',
  ),
  Roadmap(
    id: 'frontend-m3-w12-d6',
    role: 'Frontend',
    week: 12,
    day: 6,
    title: 'Documentation & Deployment',
    description: 'Document project and deploy to live environment.',
  ),
  Roadmap(
    id: 'frontend-m3-w12-d7',
    role: 'Frontend',
    week: 12,
    day: 7,
    title: 'Project: Final Capstone Project',
    description: 'Build and deploy a full-featured React web application.',
  ),
];
