import '../models/roadmap.dart';

final List<Roadmap> graphicsDesignRoadmap = [

  // -------------------------
  // Month 1
  // -------------------------

  // Week 1
  Roadmap(
    id: 'gd-m1-w1-d1',
    role: 'Graphics Designer',
    week: 1,
    day: 1,
    title: 'Introduction to Graphic Design',
    description: 'Understand the role of graphic design and basic principles.',
  ),
  Roadmap(
    id: 'gd-m1-w1-d2',
    role: 'Graphics Designer',
    week: 1,
    day: 2,
    title: 'Design Tools Overview',
    description: 'Learn the basics of Photoshop, Illustrator, and Canva.',
  ),
  Roadmap(
    id: 'gd-m1-w1-d3',
    role: 'Graphics Designer',
    week: 1,
    day: 3,
    title: 'Color Theory Basics',
    description: 'Learn primary, secondary colors, complementary colors, and palettes.',
  ),
  Roadmap(
    id: 'gd-m1-w1-d4',
    role: 'Graphics Designer',
    week: 1,
    day: 4,
    title: 'Typography Fundamentals',
    description: 'Understand font types, hierarchy, and readability.',
  ),
  Roadmap(
    id: 'gd-m1-w1-d5',
    role: 'Graphics Designer',
    week: 1,
    day: 5,
    title: 'Basic Shapes and Composition',
    description: 'Learn alignment, balance, and layout using simple shapes.',
  ),
  Roadmap(
    id: 'gd-m1-w1-d6',
    role: 'Graphics Designer',
    week: 1,
    day: 6,
    title: 'Image Editing Essentials',
    description: 'Crop, resize, and enhance images using Photoshop or GIMP.',
  ),
  Roadmap(
    id: 'gd-m1-w1-d7',
    role: 'Graphics Designer',
    week: 1,
    day: 7,
    title: 'Week 1 Project: Social Media Post Design',
    description: 'Create a simple social media post using learned tools and principles.',
  ),

  // Week 2
  Roadmap(
    id: 'gd-m1-w2-d1',
    role: 'Graphics Designer',
    week: 2,
    day: 1,
    title: 'Advanced Typography',
    description: 'Explore font pairing, hierarchy, and text effects.',
  ),
  Roadmap(
    id: 'gd-m1-w2-d2',
    role: 'Graphics Designer',
    week: 2,
    day: 2,
    title: 'Advanced Color Theory',
    description: 'Study gradients, mood boards, and color harmony.',
  ),
  Roadmap(
    id: 'gd-m1-w2-d3',
    role: 'Graphics Designer',
    week: 2,
    day: 3,
    title: 'Logo Design Basics',
    description: 'Learn to create logos with Illustrator and vector tools.',
  ),
  Roadmap(
    id: 'gd-m1-w2-d4',
    role: 'Graphics Designer',
    week: 2,
    day: 4,
    title: 'Brand Identity Introduction',
    description: 'Understand visual identity, colors, fonts, and iconography.',
  ),
  Roadmap(
    id: 'gd-m1-w2-d5',
    role: 'Graphics Designer',
    week: 2,
    day: 5,
    title: 'Poster & Flyer Design',
    description: 'Design marketing posters and flyers with effective layout.',
  ),
  Roadmap(
    id: 'gd-m1-w2-d6',
    role: 'Graphics Designer',
    week: 2,
    day: 6,
    title: 'Image Retouching & Compositing',
    description: 'Learn to remove backgrounds, blend images, and add effects.',
  ),
  Roadmap(
    id: 'gd-m1-w2-d7',
    role: 'Graphics Designer',
    week: 2,
    day: 7,
    title: 'Week 2 Project: Logo & Brand Poster',
    description: 'Design a logo and matching poster for a fictitious brand.',
  ),

  // Week 3
  Roadmap(
    id: 'gd-m1-w3-d1',
    role: 'Graphics Designer',
    week: 3,
    day: 1,
    title: 'Illustration Basics',
    description: 'Learn vector illustration using Illustrator or Affinity Designer.',
  ),
  Roadmap(
    id: 'gd-m1-w3-d2',
    role: 'Graphics Designer',
    week: 3,
    day: 2,
    title: 'Icon Design',
    description: 'Create simple icons and icon sets.',
  ),
  Roadmap(
    id: 'gd-m1-w3-d3',
    role: 'Graphics Designer',
    week: 3,
    day: 3,
    title: 'Social Media Templates',
    description: 'Design reusable social media templates.',
  ),
  Roadmap(
    id: 'gd-m1-w3-d4',
    role: 'Graphics Designer',
    week: 3,
    day: 4,
    title: 'Poster Layout & Typography',
    description: 'Combine typography and layout for visually appealing posters.',
  ),
  Roadmap(
    id: 'gd-m1-w3-d5',
    role: 'Graphics Designer',
    week: 3,
    day: 5,
    title: 'Color Grading & Filters',
    description: 'Apply color filters and grading to images.',
  ),
  Roadmap(
    id: 'gd-m1-w3-d6',
    role: 'Graphics Designer',
    week: 3,
    day: 6,
    title: 'Client Brief Understanding',
    description: 'Learn to interpret client design briefs accurately.',
  ),
  Roadmap(
    id: 'gd-m1-w3-d7',
    role: 'Graphics Designer',
    week: 3,
    day: 7,
    title: 'Week 3 Project: Branded Social Media Set',
    description: 'Design a set of social media posts and icons for a brand.',
  ),

  // Week 4
  Roadmap(
    id: 'gd-m1-w4-d1',
    role: 'Graphics Designer',
    week: 4,
    day: 1,
    title: 'Motion Graphics Basics',
    description: 'Learn animation principles and basic After Effects tools.',
  ),
  Roadmap(
    id: 'gd-m1-w4-d2',
    role: 'Graphics Designer',
    week: 4,
    day: 2,
    title: 'Animated Social Media Content',
    description: 'Create GIFs and simple animations for social media.',
  ),
  Roadmap(
    id: 'gd-m1-w4-d3',
    role: 'Graphics Designer',
    week: 4,
    day: 3,
    title: 'Banner & Ad Design',
    description: 'Design website banners, Google ads, and social media ads.',
  ),
  Roadmap(
    id: 'gd-m1-w4-d4',
    role: 'Graphics Designer',
    week: 4,
    day: 4,
    title: 'Portfolio Design Basics',
    description: 'Start organizing projects into a portfolio layout.',
  ),
  Roadmap(
    id: 'gd-m1-w4-d5',
    role: 'Graphics Designer',
    week: 4,
    day: 5,
    title: 'Advanced Image Compositing',
    description: 'Combine multiple images with masking and blending techniques.',
  ),
  Roadmap(
    id: 'gd-m1-w4-d6',
    role: 'Graphics Designer',
    week: 4,
    day: 6,
    title: 'Typography Effects',
    description: 'Create text effects for posters, flyers, and social media.',
  ),
  Roadmap(
    id: 'gd-m1-w4-d7',
    role: 'Graphics Designer',
    week: 4,
    day: 7,
    title: 'Week 4 Project: Animated Poster',
    description: 'Design an animated poster or social media ad using learned techniques.',
  ),

  // -------------------------
  // Month 2
  // -------------------------

  // Week 5
  Roadmap(
    id: 'gd-m2-w5-d1',
    role: 'Graphics Designer',
    week: 5,
    day: 1,
    title: 'Advanced Illustration',
    description: 'Create detailed vector illustrations with gradients and shading.',
  ),
  Roadmap(
    id: 'gd-m2-w5-d2',
    role: 'Graphics Designer',
    week: 5,
    day: 2,
    title: 'Branding Deep Dive',
    description: 'Study logo evolution, brand identity, and style guides.',
  ),
  Roadmap(
    id: 'gd-m2-w5-d3',
    role: 'Graphics Designer',
    week: 5,
    day: 3,
    title: 'Marketing Campaign Graphics',
    description: 'Design graphics for marketing campaigns across platforms.',
  ),
  Roadmap(
    id: 'gd-m2-w5-d4',
    role: 'Graphics Designer',
    week: 5,
    day: 4,
    title: 'Infographics Design',
    description: 'Create visual representations of data for easy understanding.',
  ),
  Roadmap(
    id: 'gd-m2-w5-d5',
    role: 'Graphics Designer',
    week: 5,
    day: 5,
    title: 'Social Media Animations',
    description: 'Animate posts, stories, and ads using After Effects or Canva Pro.',
  ),
  Roadmap(
    id: 'gd-m2-w5-d6',
    role: 'Graphics Designer',
    week: 5,
    day: 6,
    title: 'Feedback Iteration',
    description: 'Incorporate feedback from mentors and peers.',
  ),
  Roadmap(
    id: 'gd-m2-w5-d7',
    role: 'Graphics Designer',
    week: 5,
    day: 7,
    title: 'Week 5 Project: Animated Campaign Graphics',
    description: 'Create a complete animated campaign for a fictitious product.',
  ),

  // Week 6
  Roadmap(
    id: 'gd-m2-w6-d1',
    role: 'Graphics Designer',
    week: 6,
    day: 1,
    title: 'Packaging Design Basics',
    description: 'Learn to create product packaging mockups and dielines.',
  ),
  Roadmap(
    id: 'gd-m2-w6-d2',
    role: 'Graphics Designer',
    week: 6,
    day: 2,
    title: 'Social Media Branding',
    description: 'Develop consistent social media templates for a brand.',
  ),
  Roadmap(
    id: 'gd-m2-w6-d3',
    role: 'Graphics Designer',
    week: 6,
    day: 3,
    title: 'Web Graphics',
    description: 'Create graphics for websites, banners, and landing pages.',
  ),
  Roadmap(
    id: 'gd-m2-w6-d4',
    role: 'Graphics Designer',
    week: 6,
    day: 4,
    title: 'Iconography Advanced',
    description: 'Design custom icons with consistent style.',
  ),
  Roadmap(
    id: 'gd-m2-w6-d5',
    role: 'Graphics Designer',
    week: 6,
    day: 5,
    title: 'Motion Design Advanced',
    description: 'Animate illustrations and graphics for marketing.',
  ),
  Roadmap(
    id: 'gd-m2-w6-d6',
    role: 'Graphics Designer',
    week: 6,
    day: 6,
    title: 'Client Communication',
    description: 'Learn how to present designs and take client feedback.',
  ),
  Roadmap(
    id: 'gd-m2-w6-d7',
    role: 'Graphics Designer',
    week: 6,
    day: 7,
    title: 'Week 6 Project: Packaging & Animated Social Post',
    description: 'Create product packaging and animated social media post.',
  ),

  // Week 7
  Roadmap(
    id: 'gd-m2-w7-d1',
    role: 'Graphics Designer',
    week: 7,
    day: 1,
    title: 'Photo Manipulation',
    description: 'Learn advanced retouching and compositing in Photoshop.',
  ),
  Roadmap(
    id: 'gd-m2-w7-d2',
    role: 'Graphics Designer',
    week: 7,
    day: 2,
    title: 'Poster Design Advanced',
    description: 'Combine images, typography, and layout for impact.',
  ),
  Roadmap(
    id: 'gd-m2-w7-d3',
    role: 'Graphics Designer',
    week: 7,
    day: 3,
    title: 'Digital Illustration',
    description: 'Create detailed illustrations for digital campaigns.',
  ),
  Roadmap(
    id: 'gd-m2-w7-d4',
    role: 'Graphics Designer',
    week: 7,
    day: 4,
    title: 'Presentation Design',
    description: 'Design slides and presentations for professional use.',
  ),
  Roadmap(
    id: 'gd-m2-w7-d5',
    role: 'Graphics Designer',
    week: 7,
    day: 5,
    title: 'Motion Graphics Intermediate',
    description: 'Animate texts and objects for social media videos.',
  ),
  Roadmap(
    id: 'gd-m2-w7-d6',
    role: 'Graphics Designer',
    week: 7,
    day: 6,
    title: 'Portfolio Review',
    description: 'Organize and review your work for portfolio readiness.',
  ),
  Roadmap(
    id: 'gd-m2-w7-d7',
    role: 'Graphics Designer',
    week: 7,
    day: 7,
    title: 'Week 7 Project: Campaign Poster & Motion Graphic',
    description: 'Design a campaign poster and accompanying motion graphic.',
  ),

  // Week 8
  Roadmap(
    id: 'gd-m2-w8-d1',
    role: 'Graphics Designer',
    week: 8,
    day: 1,
    title: 'Advanced Branding',
    description: 'Work on brand consistency across multiple platforms.',
  ),
  Roadmap(
    id: 'gd-m2-w8-d2',
    role: 'Graphics Designer',
    week: 8,
    day: 2,
    title: 'UI Graphics Basics',
    description: 'Design interface graphics and app visuals.',
  ),
  Roadmap(
    id: 'gd-m2-w8-d3',
    role: 'Graphics Designer',
    week: 8,
    day: 3,
    title: 'Illustration for Marketing',
    description: 'Create illustrations for campaigns and ads.',
  ),
  Roadmap(
    id: 'gd-m2-w8-d4',
    role: 'Graphics Designer',
    week: 8,
    day: 4,
    title: 'Social Media Video Assets',
    description: 'Design assets for video posts, stories, and reels.',
  ),
  Roadmap(
    id: 'gd-m2-w8-d5',
    role: 'Graphics Designer',
    week: 8,
    day: 5,
    title: 'Interactive Media Design',
    description: 'Learn to design clickable and interactive media visuals.',
  ),
  Roadmap(
    id: 'gd-m2-w8-d6',
    role: 'Graphics Designer',
    week: 8,
    day: 6,
    title: 'User Feedback Iteration',
    description: 'Incorporate user and client feedback into designs.',
  ),
  Roadmap(
    id: 'gd-m2-w8-d7',
    role: 'Graphics Designer',
    week: 8,
    day: 7,
    title: 'Week 8 Project: Social Media Campaign Package',
    description: 'Create a complete social media campaign package with illustrations and motion graphics.',
  ),

  // -------------------------
  // Month 3
  // -------------------------

  // Week 9
  Roadmap(
    id: 'gd-m3-w9-d1',
    role: 'Graphics Designer',
    week: 9,
    day: 1,
    title: 'Advanced Photo Compositing',
    description: 'Combine multiple photos for creative visuals.',
  ),
  Roadmap(
    id: 'gd-m3-w9-d2',
    role: 'Graphics Designer',
    week: 9,
    day: 2,
    title: '3D Mockups',
    description: 'Learn to create 3D product mockups using Photoshop or Blender.',
  ),
  Roadmap(
    id: 'gd-m3-w9-d3',
    role: 'Graphics Designer',
    week: 9,
    day: 3,
    title: 'Typography for Marketing',
    description: 'Design typographic layouts for advertising campaigns.',
  ),
  Roadmap(
    id: 'gd-m3-w9-d4',
    role: 'Graphics Designer',
    week: 9,
    day: 4,
    title: 'Advanced Motion Graphics',
    description: 'Animate complex graphics with After Effects.',
  ),
  Roadmap(
    id: 'gd-m3-w9-d5',
    role: 'Graphics Designer',
    week: 9,
    day: 5,
    title: 'Portfolio Enhancement',
    description: 'Add advanced projects and polish existing portfolio items.',
  ),
  Roadmap(
    id: 'gd-m3-w9-d6',
    role: 'Graphics Designer',
    week: 9,
    day: 6,
    title: 'Client Presentation Skills',
    description: 'Learn to present projects professionally to clients.',
  ),
  Roadmap(
    id: 'gd-m3-w9-d7',
    role: 'Graphics Designer',
    week: 9,
    day: 7,
    title: 'Week 9 Project: 3D Product & Motion Graphic',
    description: 'Design a 3D product mockup and a related motion graphic.',
  ),

  // Week 10
  Roadmap(
    id: 'gd-m3-w10-d1',
    role: 'Graphics Designer',
    week: 10,
    day: 1,
    title: 'UI/UX Graphics Integration',
    description: 'Learn to design graphics aligned with UI/UX principles.',
  ),
  Roadmap(
    id: 'gd-m3-w10-d2',
    role: 'Graphics Designer',
    week: 10,
    day: 2,
    title: 'Advanced Branding Projects',
    description: 'Work on multi-platform branding projects.',
  ),
  Roadmap(
    id: 'gd-m3-w10-d3',
    role: 'Graphics Designer',
    week: 10,
    day: 3,
    title: 'Marketing Collateral',
    description: 'Design brochures, banners, and other promotional material.',
  ),
  Roadmap(
    id: 'gd-m3-w10-d4',
    role: 'Graphics Designer',
    week: 10,
    day: 4,
    title: 'Illustration Techniques Review',
    description: 'Refine illustration skills and techniques.',
  ),
  Roadmap(
    id: 'gd-m3-w10-d5',
    role: 'Graphics Designer',
    week: 10,
    day: 5,
    title: 'Motion Graphics for Web',
    description: 'Animate web banners and interactive graphics.',
  ),
  Roadmap(
    id: 'gd-m3-w10-d6',
    role: 'Graphics Designer',
    week: 10,
    day: 6,
    title: 'Peer Feedback',
    description: 'Review peers’ projects and provide constructive feedback.',
  ),
  Roadmap(
    id: 'gd-m3-w10-d7',
    role: 'Graphics Designer',
    week: 10,
    day: 7,
    title: 'Week 10 Project: Web Banner & Motion Graphic',
    description: 'Create a web banner and an animated motion graphic for a brand.',
  ),

  // Week 11
  Roadmap(
    id: 'gd-m3-w11-d1',
    role: 'Graphics Designer',
    week: 11,
    day: 1,
    title: 'Advanced Illustration for Branding',
    description: 'Illustrate brand mascots and marketing visuals.',
  ),
  Roadmap(
    id: 'gd-m3-w11-d2',
    role: 'Graphics Designer',
    week: 11,
    day: 2,
    title: 'Print Design',
    description: 'Learn to create business cards, flyers, and print ads.',
  ),
  Roadmap(
    id: 'gd-m3-w11-d3',
    role: 'Graphics Designer',
    week: 11,
    day: 3,
    title: 'Advanced Poster & Layout',
    description: 'Create visually engaging posters with typography focus.',
  ),
  Roadmap(
    id: 'gd-m3-w11-d4',
    role: 'Graphics Designer',
    week: 11,
    day: 4,
    title: 'Animation Portfolio',
    description: 'Add advanced motion graphics to portfolio.',
  ),
  Roadmap(
    id: 'gd-m3-w11-d5',
    role: 'Graphics Designer',
    week: 11,
    day: 5,
    title: 'Client Mockup Projects',
    description: 'Produce mockups for client feedback.',
  ),
  Roadmap(
    id: 'gd-m3-w11-d6',
    role: 'Graphics Designer',
    week: 11,
    day: 6,
    title: 'Presentation Prep',
    description: 'Prepare a final presentation of all projects.',
  ),
  Roadmap(
    id: 'gd-m3-w11-d7',
    role: 'Graphics Designer',
    week: 11,
    day: 7,
    title: 'Week 11 Project: Branding Portfolio Set',
    description: 'Compile a set of branding designs including illustrations and motion graphics.',
  ),

  // Week 12
  Roadmap(
    id: 'gd-m3-w12-d1',
    role: 'Graphics Designer',
    week: 12,
    day: 1,
    title: 'Capstone Project Planning',
    description: 'Plan a full-scale graphics project incorporating all skills learned.',
  ),
  Roadmap(
    id: 'gd-m3-w12-d2',
    role: 'Graphics Designer',
    week: 12,
    day: 2,
    title: 'Design Execution',
    description: 'Start designing the capstone project with detailed work.',
  ),
  Roadmap(
    id: 'gd-m3-w12-d3',
    role: 'Graphics Designer',
    week: 12,
    day: 3,
    title: 'Refinement & Feedback',
    description: 'Refine project designs based on feedback and testing.',
  ),
  Roadmap(
    id: 'gd-m3-w12-d4',
    role: 'Graphics Designer',
    week: 12,
    day: 4,
    title: 'Final Touches',
    description: 'Add finishing touches and polish all graphics.',
  ),
  Roadmap(
    id: 'gd-m3-w12-d5',
    role: 'Graphics Designer',
    week: 12,
    day: 5,
    title: 'Portfolio Integration',
    description: 'Integrate capstone project into professional portfolio.',
  ),
  Roadmap(
    id: 'gd-m3-w12-d6',
    role: 'Graphics Designer',
    week: 12,
    day: 6,
    title: 'Peer Review & Feedback',
    description: 'Present project to peers and mentors for critique.',
  ),
  Roadmap(
    id: 'gd-m3-w12-d7',
    role: 'Graphics Designer',
    week: 12,
    day: 7,
    title: 'Capstone Project Submission',
    description: 'Submit the final capstone project for evaluation.',
  ),
];