import '../models/roadmap.dart';

final List<Roadmap> productDesignRoadmap = [

// -------------------------
// Month 1
// -------------------------

// Week 1
Roadmap(
  id: 'pd-m1-w1-d1',
  role: 'Product Designer',
  week: 1,
  day: 1,
  title: 'Introduction to Design Tools',
  description: 'Familiarize yourself with Figma, Sketch, and Adobe XD.',
),
Roadmap(
  id: 'pd-m1-w1-d2',
  role: 'Product Designer',
  week: 1,
  day: 2,
  title: 'Design Principles Basics',
  description: 'Learn about contrast, alignment, repetition, and proximity.',
),
Roadmap(
  id: 'pd-m1-w1-d3',
  role: 'Product Designer',
  week: 1,
  day: 3,
  title: 'Typography in Design',
  description: 'Study font pairing, hierarchy, and readability.',
),
Roadmap(
  id: 'pd-m1-w1-d4',
  role: 'Product Designer',
  week: 1,
  day: 4,
  title: 'Color Theory Fundamentals',
  description: 'Understand primary, secondary, complementary colors, and palettes.',
),
Roadmap(
  id: 'pd-m1-w1-d5',
  role: 'Product Designer',
  week: 1,
  day: 5,
  title: 'Wireframing Basics',
  description: 'Sketch low-fidelity wireframes for web and mobile apps.',
),
Roadmap(
  id: 'pd-m1-w1-d6',
  role: 'Product Designer',
  week: 1,
  day: 6,
  title: 'User Research Techniques',
  description: 'Learn surveys, interviews, and personas creation.',
),
Roadmap(
  id: 'pd-m1-w1-d7',
  role: 'Product Designer',
  week: 1,
  day: 7,
  title: 'Week 1 Project: Simple Landing Page Design',
  description: 'Create a landing page wireframe using tools learned this week.',
),

// Week 2
Roadmap(
  id: 'pd-m1-w2-d1',
  role: 'Product Designer',
  week: 2,
  day: 1,
  title: 'Low-Fidelity Prototypes',
  description: 'Transform wireframes into clickable low-fidelity prototypes.',
),
Roadmap(
  id: 'pd-m1-w2-d2',
  role: 'Product Designer',
  week: 2,
  day: 2,
  title: 'UI Layout Grids',
  description: 'Learn to use grids for consistent UI layouts.',
),
Roadmap(
  id: 'pd-m1-w2-d3',
  role: 'Product Designer',
  week: 2,
  day: 3,
  title: 'Design Systems Overview',
  description: 'Understand components, typography, and colors in design systems.',
),
Roadmap(
  id: 'pd-m1-w2-d4',
  role: 'Product Designer',
  week: 2,
  day: 4,
  title: 'Icons & Imagery',
  description: 'Use iconography and images effectively in design.',
),
Roadmap(
  id: 'pd-m1-w2-d5',
  role: 'Product Designer',
  week: 2,
  day: 5,
  title: 'Feedback & Iteration',
  description: 'Learn to gather design feedback and iterate on concepts.',
),
Roadmap(
  id: 'pd-m1-w2-d6',
  role: 'Product Designer',
  week: 2,
  day: 6,
  title: 'Mobile-first Design',
  description: 'Focus on designing for mobile devices first.',
),
Roadmap(
  id: 'pd-m1-w2-d7',
  role: 'Product Designer',
  week: 2,
  day: 7,
  title: 'Week 2 Project: Mobile App Home Screen',
  description: 'Design a mobile app home screen with proper layout and UX.',
),

// Week 3
Roadmap(
  id: 'pd-m1-w3-d1',
  role: 'Product Designer',
  week: 3,
  day: 1,
  title: 'High-Fidelity Design',
  description: 'Convert low-fidelity prototypes into high-fidelity designs.',
),
Roadmap(
  id: 'pd-m1-w3-d2',
  role: 'Product Designer',
  week: 3,
  day: 2,
  title: 'Microinteractions',
  description: 'Learn small animations and interactions for better UX.',
),
Roadmap(
  id: 'pd-m1-w3-d3',
  role: 'Product Designer',
  week: 3,
  day: 3,
  title: 'UI Patterns & Components',
  description: 'Use consistent UI components for faster design workflow.',
),
Roadmap(
  id: 'pd-m1-w3-d4',
  role: 'Product Designer',
  week: 3,
  day: 4,
  title: 'Prototyping Tools',
  description: 'Create interactive prototypes in Figma or Adobe XD.',
),
Roadmap(
  id: 'pd-m1-w3-d5',
  role: 'Product Designer',
  week: 3,
  day: 5,
  title: 'Usability Testing',
  description: 'Test prototypes with users and collect feedback.',
),
Roadmap(
  id: 'pd-m1-w3-d6',
  role: 'Product Designer',
  week: 3,
  day: 6,
  title: 'Accessibility in Design',
  description: 'Ensure designs are accessible for all users.',
),
Roadmap(
  id: 'pd-m1-w3-d7',
  role: 'Product Designer',
  week: 3,
  day: 7,
  title: 'Week 3 Project: High-Fidelity App Prototype',
  description: 'Design a high-fidelity clickable app prototype based on feedback.',
),
// Week 4
Roadmap(
  id: 'pd-m1-w4-d1',
  role: 'Product Designer',
  week: 4,
  day: 1,
  title: 'Design Handoff to Developers',
  description: 'Prepare design files for developer handoff.',
),
Roadmap(
  id: 'pd-m1-w4-d2',
  role: 'Product Designer',
  week: 4,
  day: 2,
  title: 'Collaboration with Developers',
  description: 'Learn best practices for working with development teams.',
),
Roadmap(
  id: 'pd-m1-w4-d3',
  role: 'Product Designer',
  week: 4,
  day: 3,
  title: 'Design Review Processes',
  description: 'Participate in design reviews and critiques.',
),
Roadmap(
  id: 'pd-m1-w4-d4',
  role: 'Product Designer',
  week: 4,
  day: 4,
  title: 'Design Systems Implementation',
  description: 'Apply design systems to real projects.',
),
Roadmap(
  id: 'pd-m1-w4-d5',
  role: 'Product Designer',
  week: 4,
  day: 5,
  title: 'Advanced Prototyping Techniques',
  description: 'Use advanced features in prototyping tools.',
),
Roadmap(
  id: 'pd-m1-w4-d6',
  role: 'Product Designer',
  week: 4,
  day: 6,
  title: 'Design Portfolio Introduction',
  description: 'Start building your design portfolio.',
),
Roadmap(
  id: 'pd-m1-w4-d7',
  role: 'Product Designer',
  week: 4,
  day: 7,
  title: 'Week 4 Project: Complete App Design',
  description: 'Design a complete app from wireframe to high-fidelity prototype.',
),
// -------------------------
// Month 2
// -------------------------

// Week 5
Roadmap(
  id: 'pd-m2-w5-d1',
  role: 'Product Designer',
  week: 5,
  day: 1,
  title: 'Designing Onboarding Flows',
  description: 'Create smooth onboarding experiences for apps.',
),
Roadmap(
  id: 'pd-m2-w5-d2',
  role: 'Product Designer',
  week: 5,
  day: 2,
  title: 'User Journey Mapping',
  description: 'Map out user journey from start to finish.',
),
Roadmap(
  id: 'pd-m2-w5-d3',
  role: 'Product Designer',
  week: 5,
  day: 3,
  title: 'Information Architecture',
  description: 'Organize app content for easy navigation.',
),
Roadmap(
  id: 'pd-m2-w5-d4',
  role: 'Product Designer',
  week: 5,
  day: 4,
  title: 'Wireframes for Complex Screens',
  description: 'Create wireframes for multi-step forms or dashboards.',
),
Roadmap(
  id: 'pd-m2-w5-d5',
  role: 'Product Designer',
  week: 5,
  day: 5,
  title: 'Component Libraries',
  description: 'Use reusable components across screens.',
),
Roadmap(
  id: 'pd-m2-w5-d6',
  role: 'Product Designer',
  week: 5,
  day: 6,
  title: 'Design Critiques',
  description: 'Participate in critiques and iterate designs.',
),
Roadmap(
  id: 'pd-m2-w5-d7',
  role: 'Product Designer',
  week: 5,
  day: 7,
  title: 'Week 5 Project: Onboarding Flow Prototype',
  description: 'Build a full onboarding flow for an app and submit.',
),

// Week 6
Roadmap(
  id: 'pd-m2-w6-d1',
  role: 'Product Designer',
  week: 6,
  day: 1,
  title: 'Designing Dashboards',
  description: 'Learn to create clean, intuitive dashboard layouts.',
),
Roadmap(
  id: 'pd-m2-w6-d2',
  role: 'Product Designer',
  week: 6,
  day: 2,
  title: 'Data Visualization Basics',
  description: 'Use charts, graphs, and tables effectively.',
),
Roadmap(
  id: 'pd-m2-w6-d3',
  role: 'Product Designer',
  week: 6,
  day: 3,
  title: 'Interactive Components',
  description: 'Add hover states, transitions, and clickable elements.',
),
Roadmap(
  id: 'pd-m2-w6-d4',
  role: 'Product Designer',
  week: 6,
  day: 4,
  title: 'Design Handoff',
  description: 'Prepare files for developers with annotations.',
),
Roadmap(
  id: 'pd-m2-w6-d5',
  role: 'Product Designer',
  week: 6,
  day: 5,
  title: 'Responsive Dashboards',
  description: 'Ensure dashboards work on all screen sizes.',
),
Roadmap(
  id: 'pd-m2-w6-d6',
  role: 'Product Designer',
  week: 6,
  day: 6,
  title: 'User Testing Dashboards',
  description: 'Collect feedback from users and iterate designs.',
),
Roadmap(
  id: 'pd-m2-w6-d7',
  role: 'Product Designer',
  week: 6,
  day: 7,
  title: 'Week 6 Project: Dashboard Design',
  description: 'Build a responsive dashboard and submit for review.',
),

// Week 7
Roadmap(
  id: 'pd-m2-w7-d1',
  role: 'Product Designer',
  week: 7,
  day: 1,
  title: 'Designing E-commerce Flows',
  description: 'Map product browsing, cart, and checkout flows.',
),
Roadmap(
  id: 'pd-m2-w7-d2',
  role: 'Product Designer',
  week: 7,
  day: 2,
  title: 'Product Page Layouts',
  description: 'Design effective product pages with images and descriptions.',
),
Roadmap(
  id: 'pd-m2-w7-d3',
  role: 'Product Designer',
  week: 7,
  day: 3,
  title: 'Cart & Checkout Wireframes',
  description: 'Wireframe shopping cart and checkout processes.',
),
Roadmap(
  id: 'pd-m2-w7-d4',
  role: 'Product Designer',
  week: 7,
  day: 4,
  title: 'Payment Flow Designs',
  description: 'Create mock payment flows for seamless UX.',
),
Roadmap(
  id: 'pd-m2-w7-d5',
  role: 'Product Designer',
  week: 7,
  day: 5,
  title: 'Checkout Validation',
  description: 'Ensure input validation and error handling is clear.',
),
Roadmap(
  id: 'pd-m2-w7-d6',
  role: 'Product Designer',
  week: 7,
  day: 6,
  title: 'Accessibility & UX Checks',
  description: 'Test e-commerce flows for accessibility and usability.',
),
Roadmap(
  id: 'pd-m2-w7-d7',
  role: 'Product Designer',
  week: 7,
  day: 7,
  title: 'Week 7 Project: E-commerce Flow',
  description: 'Design and prototype an end-to-end e-commerce user flow.',
),

// Week 8
Roadmap(
  id: 'pd-m2-w8-d1',
  role: 'Product Designer',
  week: 8,
  day: 1,
  title: 'Design Portfolio Basics',
  description: 'Start curating your design portfolio for presentation.',
),
Roadmap(
  id: 'pd-m2-w8-d2',
  role: 'Product Designer',
  week: 8,
  day: 2,
  title: 'Portfolio Layout & Typography',
  description: 'Choose fonts and layouts that enhance your portfolio.',
),
Roadmap(
  id: 'pd-m2-w8-d3',
  role: 'Product Designer',
  week: 8,
  day: 3,
  title: 'Showcasing Projects',
  description: 'Highlight key projects effectively.',
),
Roadmap(
  id: 'pd-m2-w8-d4',
  role: 'Product Designer',
  week: 8,
  day: 4,
  title: 'Case Studies',
  description: 'Write clear case studies explaining your design decisions.',
),
Roadmap(
  id: 'pd-m2-w8-d5',
  role: 'Product Designer',
  week: 8,
  day: 5,
  title: 'Portfolio Interactions',
  description: 'Add interactive prototypes to your portfolio presentation.',
),
Roadmap(
  id: 'pd-m2-w8-d6',
  role: 'Product Designer',
  week: 8,
  day: 6,
  title: 'Feedback & Refinement',
  description: 'Seek feedback and refine portfolio pieces.',
),
Roadmap(
  id: 'pd-m2-w8-d7',
  role: 'Product Designer',
  week: 8,
  day: 7,
  title: 'Week 8 Project: Portfolio Mockup',
  description: 'Create a full portfolio mockup and submit for review.',
),

// -------------------------
// Month 3
// -------------------------

// Week 9
Roadmap(
  id: 'pd-m3-w9-d1',
  role: 'Product Designer',
  week: 9,
  day: 1,
  title: 'Advanced UX Patterns',
  description: 'Learn microinteractions, navigation patterns, and feedback systems.',
),
Roadmap(
  id: 'pd-m3-w9-d2',
  role: 'Product Designer',
  week: 9,
  day: 2,
  title: 'Designing for Multiple Devices',
  description: 'Ensure consistency across mobile, tablet, and web.',
),
Roadmap(
  id: 'pd-m3-w9-d3',
  role: 'Product Designer',
  week: 9,
  day: 3,
  title: 'Animation & Motion Design',
  description: 'Add subtle animations to improve UX.',
),
Roadmap(
  id: 'pd-m3-w9-d4',
  role: 'Product Designer',
  week: 9,
  day: 4,
  title: 'Advanced Prototyping',
  description: 'Use advanced prototyping features for realistic user flows.',
),
Roadmap(
  id: 'pd-m3-w9-d5',
  role: 'Product Designer',
  week: 9,
  day: 5,
  title: 'Collaboration Tools',
  description: 'Learn Figma collaboration, commenting, and version control.',
),
Roadmap(
  id: 'pd-m3-w9-d6',
  role: 'Product Designer',
  week: 9,
  day: 6,
  title: 'User Testing & Iteration',
  description: 'Test your prototypes and iterate based on results.',
),
Roadmap(
  id: 'pd-m3-w9-d7',
  role: 'Product Designer',
  week: 9,
  day: 7,
  title: 'Week 9 Project: Multi-Device App Prototype',
  description: 'Design and prototype an app for mobile, tablet, and web.',
),

// Week 10
Roadmap(
  id: 'pd-m3-w10-d1',
  role: 'Product Designer',
  week: 10,
  day: 1,
  title: 'Design Handoff & Documentation',
  description: 'Prepare designs and assets for developers.',
),
Roadmap(
  id: 'pd-m3-w10-d2',
  role: 'Product Designer',
  week: 10,
  day: 2,
  title: 'Working with Development Teams',
  description: 'Learn best practices for developer collaboration.',
),
Roadmap(
  id: 'pd-m3-w10-d3',
  role: 'Product Designer',
  week: 10,
  day: 3,
  title: 'Design System Scaling',
  description: 'Apply design systems to larger projects.',
),
Roadmap(
  id: 'pd-m3-w10-d4',
  role: 'Product Designer',
  week: 10,
  day: 4,
  title: 'Advanced Accessibility',
  description: 'Ensure inclusive designs for all users.',
),
Roadmap(
  id: 'pd-m3-w10-d5',
  role: 'Product Designer',
  week: 10,
  day: 5,
  title: 'Portfolio Enhancement',
  description: 'Add polished projects and case studies.',
),
Roadmap(
  id: 'pd-m3-w10-d6',
  role: 'Product Designer',
  week: 10,
  day: 6,
  title: 'Peer Feedback Sessions',
  description: 'Present portfolio and get feedback from peers.',
),
Roadmap(
  id: 'pd-m3-w10-d7',
  role: 'Product Designer',
  week: 10,
  day: 7,
  title: 'Week 10 Project: Full Product Case Study',
  description: 'Create a comprehensive case study and submit.',
),

// Week 11
Roadmap(
  id: 'pd-m3-w11-d1',
  role: 'Product Designer',
  week: 11,
  day: 1,
  title: 'Real-world UX Challenges',
  description: 'Analyze existing apps and propose improvements.',
),
Roadmap(
  id: 'pd-m3-w11-d2',
  role: 'Product Designer',
  week: 11,
  day: 2,
  title: 'Heuristic Evaluation',
  description: 'Evaluate apps based on usability heuristics.',
),
Roadmap(
  id: 'pd-m3-w11-d3',
  role: 'Product Designer',
  week: 11,
  day: 3,
  title: 'Interaction Design Patterns',
  description: 'Apply consistent interaction patterns.',
),
Roadmap(
  id: 'pd-m3-w11-d4',
  role: 'Product Designer',
  week: 11,
  day: 4,
  title: 'UI Consistency Checks',
  description: 'Ensure all screens and components are consistent.',
),
Roadmap(
  id: 'pd-m3-w11-d5',
  role: 'Product Designer',
  week: 11,
  day: 5,
  title: 'Design Mentorship',
  description: 'Seek guidance from senior designers.',
),
Roadmap(
  id: 'pd-m3-w11-d6',
  role: 'Product Designer',
  week: 11,
  day: 6,
  title: 'Portfolio Refinement',
  description: 'Refine portfolio based on mentorship feedback.',
),
Roadmap(
  id: 'pd-m3-w11-d7',
  role: 'Product Designer',
  week: 11,
  day: 7,
  title: 'Week 11 Project: UX Improvement Proposal',
  description: 'Submit redesign of an existing app with improvements.',
),

// Week 12
Roadmap(
  id: 'pd-m3-w12-d1',
  role: 'Product Designer',
  week: 12,
  day: 1,
  title: 'Capstone Project Planning',
  description: 'Plan your final 3-month capstone project.',
),
Roadmap(
  id: 'pd-m3-w12-d2',
  role: 'Product Designer',
  week: 12,
  day: 2,
  title: 'Wireframes & Prototypes',
  description: 'Create wireframes and interactive prototypes for your capstone.',
),
Roadmap(
  id: 'pd-m3-w12-d3',
  role: 'Product Designer',
  week: 12,
  day: 3,
  title: 'Design Review Sessions',
  description: 'Get feedback from mentors and peers.',
),
Roadmap(
  id: 'pd-m3-w12-d4',
  role: 'Product Designer',
  week: 12,
  day: 4,
  title: 'Polishing & Final Touches',
  description: 'Refine the design for presentation.',
),
Roadmap(
  id: 'pd-m3-w12-d5',
  role: 'Product Designer',
  week: 12,
  day: 5,
  title: 'Interactive Prototype Testing',
  description: 'Test your capstone project prototype.',
),
Roadmap(
  id: 'pd-m3-w12-d6',
  role: 'Product Designer',
  week: 12,
  day: 6,
  title: 'Portfolio Integration',
  description: 'Include capstone project in your portfolio.',
),
Roadmap(
  id: 'pd-m3-w12-d7',
  role: 'Product Designer',
  week: 12,
  day: 7,
  title: 'Week 12 Project: Capstone Submission',
  description: 'Submit your final capstone project for review.',
),

];