import '../models/roadmap.dart';

final List<Roadmap> projectManagementRoadmap = [
  // =========================
  // Project Manager Roadmap
  // =========================

  // -------------------------
  // Month 1
  // -------------------------

  // Week 1
  Roadmap(
    id: 'pm-m1-w1-d1',
    role: 'Project Manager',
    week: 1,
    day: 1,
    title: 'Introduction to Project Management',
    description: 'Understand the fundamentals and responsibilities of a PM.',
  ),
  Roadmap(
    id: 'pm-m1-w1-d2',
    role: 'Project Manager',
    week: 1,
    day: 2,
    title: 'Project Lifecycle Overview',
    description: 'Learn phases: Initiation, Planning, Execution, Monitoring, Closing.',
  ),
  Roadmap(
    id: 'pm-m1-w1-d3',
    role: 'Project Manager',
    week: 1,
    day: 3,
    title: 'Stakeholder Management',
    description: 'Identify stakeholders and their influence on projects.',
  ),
  Roadmap(
    id: 'pm-m1-w1-d4',
    role: 'Project Manager',
    week: 1,
    day: 4,
    title: 'Communication Skills',
    description: 'Effective communication techniques for PMs.',
  ),
  Roadmap(
    id: 'pm-m1-w1-d5',
    role: 'Project Manager',
    week: 1,
    day: 5,
    title: 'Tools Overview',
    description: 'Introduction to project management tools like Jira and Trello.',
  ),
  Roadmap(
    id: 'pm-m1-w1-d6',
    role: 'Project Manager',
    week: 1,
    day: 6,
    title: 'Team Collaboration',
    description: 'Learn how to work effectively with teams.',
  ),
  Roadmap(
    id: 'pm-m1-w1-d7',
    role: 'Project Manager',
    week: 1,
    day: 7,
    title: 'Week 1 Project: Project Charter',
    description: 'Create a project charter for a sample project.',
  ),

  // Week 2
  Roadmap(
    id: 'pm-m1-w2-d1',
    role: 'Project Manager',
    week: 2,
    day: 1,
    title: 'Scope Management',
    description: 'Define project scope and avoid scope creep.',
  ),
  Roadmap(
    id: 'pm-m1-w2-d2',
    role: 'Project Manager',
    week: 2,
    day: 2,
    title: 'Work Breakdown Structure',
    description: 'Break project deliverables into manageable tasks.',
  ),
  Roadmap(
    id: 'pm-m1-w2-d3',
    role: 'Project Manager',
    week: 2,
    day: 3,
    title: 'Time Management',
    description: 'Estimate task durations and create timelines.',
  ),
  Roadmap(
    id: 'pm-m1-w2-d4',
    role: 'Project Manager',
    week: 2,
    day: 4,
    title: 'Risk Management',
    description: 'Identify, assess, and mitigate project risks.',
  ),
  Roadmap(
    id: 'pm-m1-w2-d5',
    role: 'Project Manager',
    week: 2,
    day: 5,
    title: 'Budgeting Basics',
    description: 'Introduction to project budgeting and cost control.',
  ),
  Roadmap(
    id: 'pm-m1-w2-d6',
    role: 'Project Manager',
    week: 2,
    day: 6,
    title: 'Resource Allocation',
    description: 'Assign resources efficiently for project tasks.',
  ),
  Roadmap(
    id: 'pm-m1-w2-d7',
    role: 'Project Manager',
    week: 2,
    day: 7,
    title: 'Week 2 Project: WBS & Timeline',
    description: 'Create a Work Breakdown Structure and Gantt chart for a sample project.',
  ),

  // Week 3
  Roadmap(
    id: 'pm-m1-w3-d1',
    role: 'Project Manager',
    week: 3,
    day: 1,
    title: 'Quality Management',
    description: 'Learn techniques to ensure project deliverables meet standards.',
  ),
  Roadmap(
    id: 'pm-m1-w3-d2',
    role: 'Project Manager',
    week: 3,
    day: 2,
    title: 'Agile Fundamentals',
    description: 'Understand Agile principles and frameworks.',
  ),
  Roadmap(
    id: 'pm-m1-w3-d3',
    role: 'Project Manager',
    week: 3,
    day: 3,
    title: 'Scrum Basics',
    description: 'Introduction to Scrum roles, ceremonies, and artifacts.',
  ),
  Roadmap(
    id: 'pm-m1-w3-d4',
    role: 'Project Manager',
    week: 3,
    day: 4,
    title: 'Sprint Planning',
    description: 'Learn how to plan sprints and assign tasks.',
  ),
  Roadmap(
    id: 'pm-m1-w3-d5',
    role: 'Project Manager',
    week: 3,
    day: 5,
    title: 'Daily Standups',
    description: 'Conduct daily stand-up meetings efficiently.',
  ),
  Roadmap(
    id: 'pm-m1-w3-d6',
    role: 'Project Manager',
    week: 3,
    day: 6,
    title: 'Sprint Review & Retrospective',
    description: 'Learn how to review sprint outcomes and improve processes.',
  ),
  Roadmap(
    id: 'pm-m1-w3-d7',
    role: 'Project Manager',
    week: 3,
    day: 7,
    title: 'Week 3 Project: Agile Sprint Simulation',
    description: 'Plan and execute a mini sprint with your team.',
  ),

  // Week 4
  Roadmap(
    id: 'pm-m1-w4-d1',
    role: 'Project Manager',
    week: 4,
    day: 1,
    title: 'Kanban Basics',
    description: 'Learn how to visualize work and manage flow using Kanban.',
  ),
  Roadmap(
    id: 'pm-m1-w4-d2',
    role: 'Project Manager',
    week: 4,
    day: 2,
    title: 'Project Documentation',
    description: 'Prepare and manage essential project documents.',
  ),
  Roadmap(
    id: 'pm-m1-w4-d3',
    role: 'Project Manager',
    week: 4,
    day: 3,
    title: 'Change Management',
    description: 'Manage project changes effectively.',
  ),
  Roadmap(
    id: 'pm-m1-w4-d4',
    role: 'Project Manager',
    week: 4,
    day: 4,
    title: 'Conflict Resolution',
    description: 'Handle conflicts within the project team.',
  ),
  Roadmap(
    id: 'pm-m1-w4-d5',
    role: 'Project Manager',
    week: 4,
    day: 5,
    title: 'Vendor Management',
    description: 'Learn how to manage third-party vendors.',
  ),
  Roadmap(
    id: 'pm-m1-w4-d6',
    role: 'Project Manager',
    week: 4,
    day: 6,
    title: 'Leadership Skills',
    description: 'Develop leadership qualities for project management.',
  ),
  Roadmap(
    id: 'pm-m1-w4-d7',
    role: 'Project Manager',
    week: 4,
    day: 7,
    title: 'Week 4 Project: Project Plan Documentation',
    description: 'Create a complete project plan including scope, timeline, and budget.',
  ),
  // =========================
  // Month 2
  // =========================

  // Week 5
  Roadmap(
    id: 'pm-m2-w5-d1',
    role: 'Project Manager',
    week: 5,
    day: 1,
    title: 'Advanced Agile Concepts',
    description: 'Explore scaling Agile and hybrid approaches.',
  ),
  Roadmap(
    id: 'pm-m2-w5-d2',
    role: 'Project Manager',
    week: 5,
    day: 2,
    title: 'Risk Assessment Techniques',
    description: 'Perform detailed risk analysis for projects.',
  ),
  Roadmap(
    id: 'pm-m2-w5-d3',
    role: 'Project Manager',
    week: 5,
    day: 3,
    title: 'Earned Value Management',
    description: 'Learn how to measure project performance using EVM.',
  ),
  Roadmap(
    id: 'pm-m2-w5-d4',
    role: 'Project Manager',
    week: 5,
    day: 4,
    title: 'Advanced Scheduling',
    description: 'Create complex schedules with dependencies and constraints.',
  ),
  Roadmap(
    id: 'pm-m2-w5-d5',
    role: 'Project Manager',
    week: 5,
    day: 5,
    title: 'Cost Management',
    description: 'Control project costs and budget effectively.',
  ),
  Roadmap(
    id: 'pm-m2-w5-d6',
    role: 'Project Manager',
    week: 5,
    day: 6,
    title: 'Project Reporting',
    description: 'Prepare detailed reports for stakeholders.',
  ),
  Roadmap(
    id: 'pm-m2-w5-d7',
    role: 'Project Manager',
    week: 5,
    day: 7,
    title: 'Week 5 Project: Risk & Cost Plan',
    description: 'Develop a detailed risk assessment and budget plan for a sample project.',
  ),

  // Week 6
  Roadmap(
    id: 'pm-m2-w6-d1',
    role: 'Project Manager',
    week: 6,
    day: 1,
    title: 'Team Motivation Techniques',
    description: 'Learn strategies to motivate your project team.',
  ),
  Roadmap(
    id: 'pm-m2-w6-d2',
    role: 'Project Manager',
    week: 6,
    day: 2,
    title: 'Stakeholder Communication Plan',
    description: 'Design a communication plan tailored for all stakeholders.',
  ),
  Roadmap(
    id: 'pm-m2-w6-d3',
    role: 'Project Manager',
    week: 6,
    day: 3,
    title: 'Leadership in Agile',
    description: 'Explore servant leadership and team facilitation techniques.',
  ),
  Roadmap(
    id: 'pm-m2-w6-d4',
    role: 'Project Manager',
    week: 6,
    day: 4,
    title: 'Conflict Resolution Strategies',
    description: 'Advanced methods to resolve conflicts and improve team collaboration.',
  ),
  Roadmap(
    id: 'pm-m2-w6-d5',
    role: 'Project Manager',
    week: 6,
    day: 5,
    title: 'Quality Audits',
    description: 'Perform audits to ensure quality standards are met.',
  ),
  Roadmap(
    id: 'pm-m2-w6-d6',
    role: 'Project Manager',
    week: 6,
    day: 6,
    title: 'Change Control Board',
    description: 'Understand the process of evaluating and approving project changes.',
  ),
  Roadmap(
    id: 'pm-m2-w6-d7',
    role: 'Project Manager',
    week: 6,
    day: 7,
    title: 'Week 6 Project: Stakeholder & Change Plan',
    description: 'Develop a stakeholder communication plan and change management process.',
  ),

  // Week 7
  Roadmap(
    id: 'pm-m2-w7-d1',
    role: 'Project Manager',
    week: 7,
    day: 1,
    title: 'Vendor Evaluation',
    description: 'Learn how to assess vendor capabilities and fit.',
  ),
  Roadmap(
    id: 'pm-m2-w7-d2',
    role: 'Project Manager',
    week: 7,
    day: 2,
    title: 'Contract Management',
    description: 'Understand contractual obligations and monitoring.',
  ),
  Roadmap(
    id: 'pm-m2-w7-d3',
    role: 'Project Manager',
    week: 7,
    day: 3,
    title: 'Project Auditing',
    description: 'Perform audits to ensure compliance and effectiveness.',
  ),
  Roadmap(
    id: 'pm-m2-w7-d4',
    role: 'Project Manager',
    week: 7,
    day: 4,
    title: 'Leadership Feedback',
    description: 'Implement feedback sessions with team members.',
  ),
  Roadmap(
    id: 'pm-m2-w7-d5',
    role: 'Project Manager',
    week: 7,
    day: 5,
    title: 'Performance Metrics',
    description: 'Measure project success using KPIs and metrics.',
  ),
  Roadmap(
    id: 'pm-m2-w7-d6',
    role: 'Project Manager',
    week: 7,
    day: 6,
    title: 'Project Closing Techniques',
    description: 'Learn to close projects effectively, including lessons learned.',
  ),
  Roadmap(
    id: 'pm-m2-w7-d7',
    role: 'Project Manager',
    week: 7,
    day: 7,
    title: 'Week 7 Project: Vendor & Performance Report',
    description: 'Evaluate vendor performance and prepare project performance report.',
  ),

  // Week 8
  Roadmap(
    id: 'pm-m2-w8-d1',
    role: 'Project Manager',
    week: 8,
    day: 1,
    title: 'Advanced Scheduling Techniques',
    description: 'Handle overlapping tasks and resource leveling.',
  ),
  Roadmap(
    id: 'pm-m2-w8-d2',
    role: 'Project Manager',
    week: 8,
    day: 2,
    title: 'Risk Mitigation Plans',
    description: 'Develop strategies to mitigate high-impact risks.',
  ),
  Roadmap(
    id: 'pm-m2-w8-d3',
    role: 'Project Manager',
    week: 8,
    day: 3,
    title: 'Agile Retrospectives',
    description: 'Run effective retrospective sessions for continuous improvement.',
  ),
  Roadmap(
    id: 'pm-m2-w8-d4',
    role: 'Project Manager',
    week: 8,
    day: 4,
    title: 'Documentation Review',
    description: 'Check all project documentation for completeness.',
  ),
  Roadmap(
    id: 'pm-m2-w8-d5',
    role: 'Project Manager',
    week: 8,
    day: 5,
    title: 'Team Training Planning',
    description: 'Plan necessary training sessions for team members.',
  ),
  Roadmap(
    id: 'pm-m2-w8-d6',
    role: 'Project Manager',
    week: 8,
    day: 6,
    title: 'Final Preparations',
    description: 'Prepare all materials and resources for project execution.',
  ),
  Roadmap(
    id: 'pm-m2-w8-d7',
    role: 'Project Manager',
    week: 8,
    day: 7,
    title: 'Week 8 Project: Complete Project Simulation',
    description: 'Execute a full project simulation covering planning, execution, and closing.',
  ),
  // =========================
  // Month 3
  // =========================

  // Week 9
  Roadmap(
    id: 'pm-m3-w9-d1',
    role: 'Project Manager',
    week: 9,
    day: 1,
    title: 'Portfolio Management',
    description: 'Learn how to manage multiple projects and align them with business goals.',
  ),
  Roadmap(
    id: 'pm-m3-w9-d2',
    role: 'Project Manager',
    week: 9,
    day: 2,
    title: 'Advanced Resource Allocation',
    description: 'Optimize resources across multiple projects efficiently.',
  ),
  Roadmap(
    id: 'pm-m3-w9-d3',
    role: 'Project Manager',
    week: 9,
    day: 3,
    title: 'Stakeholder Influence',
    description: 'Techniques to influence stakeholders and manage expectations.',
  ),
  Roadmap(
    id: 'pm-m3-w9-d4',
    role: 'Project Manager',
    week: 9,
    day: 4,
    title: 'Governance Frameworks',
    description: 'Understand governance frameworks for project oversight.',
  ),
  Roadmap(
    id: 'pm-m3-w9-d5',
    role: 'Project Manager',
    week: 9,
    day: 5,
    title: 'Compliance Management',
    description: 'Ensure projects adhere to organizational and legal standards.',
  ),
  Roadmap(
    id: 'pm-m3-w9-d6',
    role: 'Project Manager',
    week: 9,
    day: 6,
    title: 'Risk Auditing',
    description: 'Conduct risk audits to identify and mitigate potential issues.',
  ),
  Roadmap(
    id: 'pm-m3-w9-d7',
    role: 'Project Manager',
    week: 9,
    day: 7,
    title: 'Week 9 Project: Portfolio Risk & Compliance',
    description: 'Create a portfolio report with risk assessment and compliance plan.',
  ),

  // Week 10
  Roadmap(
    id: 'pm-m3-w10-d1',
    role: 'Project Manager',
    week: 10,
    day: 1,
    title: 'Change Leadership',
    description: 'Lead organizational change effectively within projects.',
  ),
  Roadmap(
    id: 'pm-m3-w10-d2',
    role: 'Project Manager',
    week: 10,
    day: 2,
    title: 'Project Innovation Techniques',
    description: 'Foster innovation within projects to deliver added value.',
  ),
  Roadmap(
    id: 'pm-m3-w10-d3',
    role: 'Project Manager',
    week: 10,
    day: 3,
    title: 'Performance Review Techniques',
    description: 'Conduct effective project and team performance reviews.',
  ),
  Roadmap(
    id: 'pm-m3-w10-d4',
    role: 'Project Manager',
    week: 10,
    day: 4,
    title: 'Advanced Reporting Dashboards',
    description: 'Design dashboards for real-time project insights.',
  ),
  Roadmap(
    id: 'pm-m3-w10-d5',
    role: 'Project Manager',
    week: 10,
    day: 5,
    title: 'Knowledge Management',
    description: 'Capture and share lessons learned across projects.',
  ),
  Roadmap(
    id: 'pm-m3-w10-d6',
    role: 'Project Manager',
    week: 10,
    day: 6,
    title: 'Conflict Mediation',
    description: 'Resolve high-level conflicts within and across projects.',
  ),
  Roadmap(
    id: 'pm-m3-w10-d7',
    role: 'Project Manager',
    week: 10,
    day: 7,
    title: 'Week 10 Project: Innovation & Reporting Plan',
    description: 'Prepare an innovative project plan with performance dashboards.',
  ),

  // Week 11
  Roadmap(
    id: 'pm-m3-w11-d1',
    role: 'Project Manager',
    week: 11,
    day: 1,
    title: 'Advanced Stakeholder Mapping',
    description: 'Map and categorize stakeholders to optimize engagement.',
  ),
  Roadmap(
    id: 'pm-m3-w11-d2',
    role: 'Project Manager',
    week: 11,
    day: 2,
    title: 'Budget Forecasting',
    description: 'Predict and plan budgets for long-term project cycles.',
  ),
  Roadmap(
    id: 'pm-m3-w11-d3',
    role: 'Project Manager',
    week: 11,
    day: 3,
    title: 'Performance Metrics Optimization',
    description: 'Improve KPIs and metrics tracking for maximum efficiency.',
  ),
  Roadmap(
    id: 'pm-m3-w11-d4',
    role: 'Project Manager',
    week: 11,
    day: 4,
    title: 'Team Capability Analysis',
    description: 'Analyze and improve team skill sets for project success.',
  ),
  Roadmap(
    id: 'pm-m3-w11-d5',
    role: 'Project Manager',
    week: 11,
    day: 5,
    title: 'Portfolio Reporting',
    description: 'Compile comprehensive portfolio performance reports.',
  ),
  Roadmap(
    id: 'pm-m3-w11-d6',
    role: 'Project Manager',
    week: 11,
    day: 6,
    title: 'Lessons Learned Workshop',
    description: 'Conduct workshops to extract valuable lessons.',
  ),
  Roadmap(
    id: 'pm-m3-w11-d7',
    role: 'Project Manager',
    week: 11,
    day: 7,
    title: 'Week 11 Project: Portfolio Review & Workshop',
    description: 'Prepare a full portfolio review and conduct a lessons-learned workshop.',
  ),

  // Week 12
  Roadmap(
    id: 'pm-m3-w12-d1',
    role: 'Project Manager',
    week: 12,
    day: 1,
    title: 'Strategic Roadmapping',
    description: 'Develop a long-term roadmap aligned with company strategy.',
  ),
  Roadmap(
    id: 'pm-m3-w12-d2',
    role: 'Project Manager',
    week: 12,
    day: 2,
    title: 'Executive Presentations',
    description: 'Prepare and deliver executive-level project presentations.',
  ),
  Roadmap(
    id: 'pm-m3-w12-d3',
    role: 'Project Manager',
    week: 12,
    day: 3,
    title: 'Advanced Risk Scenarios',
    description: 'Plan for multiple high-risk scenarios and mitigation plans.',
  ),
  Roadmap(
    id: 'pm-m3-w12-d4',
    role: 'Project Manager',
    week: 12,
    day: 4,
    title: 'Organizational Alignment',
    description: 'Ensure projects align with organizational goals and strategy.',
  ),
  Roadmap(
    id: 'pm-m3-w12-d5',
    role: 'Project Manager',
    week: 12,
    day: 5,
    title: 'Team Succession Planning',
    description: 'Plan for future leadership and key roles in the team.',
  ),
  Roadmap(
    id: 'pm-m3-w12-d6',
    role: 'Project Manager',
    week: 12,
    day: 6,
    title: 'Final Review & Retrospective',
    description: 'Conduct a final review of all projects and retrospective analysis.',
  ),
  Roadmap(
    id: 'pm-m3-w12-d7',
    role: 'Project Manager',
    week: 12,
    day: 7,
    title: 'Week 12 Project: Capstone Project Simulation',
    description: 'Execute a capstone project covering full PM lifecycle, including planning, execution, risk management, and review.',
  ),
];