import '../models/roadmap.dart';

final List<Roadmap> socialMediaManagementRoadmap = [
  // -------------------------
  // Month 1
  // -------------------------

  // Week 1
  Roadmap(
    id: 'smm-m1-w1-d1',
    role: 'Social Media Manager',
    week: 1,
    day: 1,
    title: 'Social Media Platforms Overview',
    description: 'Understand the key social media platforms and their audiences.',
  ),
  Roadmap(
    id: 'smm-m1-w1-d2',
    role: 'Social Media Manager',
    week: 1,
    day: 2,
    title: 'Content Planning Basics',
    description: 'Learn to plan content calendars and schedules.',
  ),
  Roadmap(
    id: 'smm-m1-w1-d3',
    role: 'Social Media Manager',
    week: 1,
    day: 3,
    title: 'Audience Research',
    description: 'Identify target audience and engagement strategies.',
  ),
  Roadmap(
    id: 'smm-m1-w1-d4',
    role: 'Social Media Manager',
    week: 1,
    day: 4,
    title: 'Content Creation Tools',
    description: 'Familiarize with tools like Canva, Photoshop, and video editors.',
  ),
  Roadmap(
    id: 'smm-m1-w1-d5',
    role: 'Social Media Manager',
    week: 1,
    day: 5,
    title: 'Post Scheduling',
    description: 'Learn to schedule posts using tools like Buffer or Hootsuite.',
  ),
  Roadmap(
    id: 'smm-m1-w1-d6',
    role: 'Social Media Manager',
    week: 1,
    day: 6,
    title: 'Engagement & Analytics Basics',
    description: 'Track likes, shares, and comments to measure engagement.',
  ),
  Roadmap(
    id: 'smm-m1-w1-d7',
    role: 'Social Media Manager',
    week: 1,
    day: 7,
    title: 'Week 1 Project: First Week Social Campaign',
    description: 'Plan and create a 1-week social media content schedule and sample posts.',
  ),

  // Week 2
  Roadmap(
    id: 'smm-m1-w2-d1',
    role: 'Social Media Manager',
    week: 2,
    day: 1,
    title: 'Advanced Content Planning',
    description: 'Plan content across multiple platforms for consistency.',
  ),
  Roadmap(
    id: 'smm-m1-w2-d2',
    role: 'Social Media Manager',
    week: 2,
    day: 2,
    title: 'Graphic Content Creation',
    description: 'Design visually appealing graphics for posts and ads.',
  ),
  Roadmap(
    id: 'smm-m1-w2-d3',
    role: 'Social Media Manager',
    week: 2,
    day: 3,
    title: 'Video Content Creation',
    description: 'Create short videos for reels, stories, and ads.',
  ),
  Roadmap(
    id: 'smm-m1-w2-d4',
    role: 'Social Media Manager',
    week: 2,
    day: 4,
    title: 'Content Optimization',
    description: 'Optimize posts for engagement and reach.',
  ),
  Roadmap(
    id: 'smm-m1-w2-d5',
    role: 'Social Media Manager',
    week: 2,
    day: 5,
    title: 'Analytics Deep Dive',
    description: 'Learn to interpret platform insights and metrics.',
  ),
  Roadmap(
    id: 'smm-m1-w2-d6',
    role: 'Social Media Manager',
    week: 2,
    day: 6,
    title: 'Community Management',
    description: 'Engage with followers and handle online community interactions.',
  ),
  Roadmap(
    id: 'smm-m1-w2-d7',
    role: 'Social Media Manager',
    week: 2,
    day: 7,
    title: 'Week 2 Project: Multi-Platform Campaign',
    description: 'Create graphics, videos, and a posting plan for a multi-platform campaign.',
  ),

  // Week 3
  Roadmap(
    id: 'smm-m1-w3-d1',
    role: 'Social Media Manager',
    week: 3,
    day: 1,
    title: 'Hashtag Strategy',
    description: 'Learn to research and use effective hashtags.',
  ),
  Roadmap(
    id: 'smm-m1-w3-d2',
    role: 'Social Media Manager',
    week: 3,
    day: 2,
    title: 'Paid Ads Overview',
    description: 'Introduction to running social media ads and budgets.',
  ),
  Roadmap(
    id: 'smm-m1-w3-d3',
    role: 'Social Media Manager',
    week: 3,
    day: 3,
    title: 'Campaign Scheduling',
    description: 'Plan campaigns according to key dates and audience activity.',
  ),
  Roadmap(
    id: 'smm-m1-w3-d4',
    role: 'Social Media Manager',
    week: 3,
    day: 4,
    title: 'Content Testing',
    description: 'A/B test posts and analyze performance.',
  ),
  Roadmap(
    id: 'smm-m1-w3-d5',
    role: 'Social Media Manager',
    week: 3,
    day: 5,
    title: 'Collaboration Tools',
    description: 'Use tools like Trello, Notion for team management.',
  ),
  Roadmap(
    id: 'smm-m1-w3-d6',
    role: 'Social Media Manager',
    week: 3,
    day: 6,
    title: 'Crisis Management',
    description: 'Learn to handle negative feedback or social media crises.',
  ),
  Roadmap(
    id: 'smm-m1-w3-d7',
    role: 'Social Media Manager',
    week: 3,
    day: 7,
    title: 'Week 3 Project: Hashtag & Engagement Campaign',
    description: 'Create a campaign focusing on hashtags and follower engagement.',
  ),

  // Week 4
  Roadmap(
    id: 'smm-m1-w4-d1',
    role: 'Social Media Manager',
    week: 4,
    day: 1,
    title: 'Influencer Marketing Basics',
    description: 'Learn to identify and reach out to influencers.',
  ),
  Roadmap(
    id: 'smm-m1-w4-d2',
    role: 'Social Media Manager',
    week: 4,
    day: 2,
    title: 'Collaboration Content',
    description: 'Create posts for influencer collaborations.',
  ),
  Roadmap(
    id: 'smm-m1-w4-d3',
    role: 'Social Media Manager',
    week: 4,
    day: 3,
    title: 'Engagement Metrics',
    description: 'Track likes, comments, shares, and conversions.',
  ),
  Roadmap(
    id: 'smm-m1-w4-d4',
    role: 'Social Media Manager',
    week: 4,
    day: 4,
    title: 'Analytics Reporting',
    description: 'Generate reports for campaigns using insights tools.',
  ),
  Roadmap(
    id: 'smm-m1-w4-d5',
    role: 'Social Media Manager',
    week: 4,
    day: 5,
    title: 'Advanced Scheduling',
    description: 'Plan recurring campaigns with automated posting.',
  ),
  Roadmap(
    id: 'smm-m1-w4-d6',
    role: 'Social Media Manager',
    week: 4,
    day: 6,
    title: 'Content Refinement',
    description: 'Improve post quality using design and copy techniques.',
  ),
  Roadmap(
    id: 'smm-m1-w4-d7',
    role: 'Social Media Manager',
    week: 4,
    day: 7,
    title: 'Week 4 Project: Influencer & Engagement Campaign',
    description: 'Design a full campaign including influencer posts, engagement posts, and reporting.',
  ),
  // -------------------------
  // Month 2
  // -------------------------

  // Week 5
  Roadmap(
    id: 'smm-m2-w5-d1',
    role: 'Social Media Manager',
    week: 5,
    day: 1,
    title: 'Content Ideation Techniques',
    description: 'Brainstorm creative content ideas for different campaigns.',
  ),
  Roadmap(
    id: 'smm-m2-w5-d2',
    role: 'Social Media Manager',
    week: 5,
    day: 2,
    title: 'Video Editing Basics',
    description: 'Learn basic editing for social media videos.',
  ),
  Roadmap(
    id: 'smm-m2-w5-d3',
    role: 'Social Media Manager',
    week: 5,
    day: 3,
    title: 'Storytelling in Social Media',
    description: 'Craft compelling stories for posts and campaigns.',
  ),
  Roadmap(
    id: 'smm-m2-w5-d4',
    role: 'Social Media Manager',
    week: 5,
    day: 4,
    title: 'Brand Voice Consistency',
    description: 'Maintain consistent tone and style across platforms.',
  ),
  Roadmap(
    id: 'smm-m2-w5-d5',
    role: 'Social Media Manager',
    week: 5,
    day: 5,
    title: 'Content Calendar Review',
    description: 'Analyze content calendar for gaps and improvements.',
  ),
  Roadmap(
    id: 'smm-m2-w5-d6',
    role: 'Social Media Manager',
    week: 5,
    day: 6,
    title: 'Engagement Techniques',
    description: 'Experiment with polls, quizzes, and interactive content.',
  ),
  Roadmap(
    id: 'smm-m2-w5-d7',
    role: 'Social Media Manager',
    week: 5,
    day: 7,
    title: 'Week 5 Project: Interactive Content Campaign',
    description: 'Plan and create a week-long interactive content campaign.',
  ),

  // Week 6
  Roadmap(
    id: 'smm-m2-w6-d1',
    role: 'Social Media Manager',
    week: 6,
    day: 1,
    title: 'Analytics Deep Dive',
    description: 'Analyze engagement metrics to identify trends.',
  ),
  Roadmap(
    id: 'smm-m2-w6-d2',
    role: 'Social Media Manager',
    week: 6,
    day: 2,
    title: 'Target Audience Segmentation',
    description: 'Segment audience for better campaign targeting.',
  ),
  Roadmap(
    id: 'smm-m2-w6-d3',
    role: 'Social Media Manager',
    week: 6,
    day: 3,
    title: 'Social Media Advertising',
    description: 'Set up ads campaigns on platforms like Facebook & Instagram.',
  ),
  Roadmap(
    id: 'smm-m2-w6-d4',
    role: 'Social Media Manager',
    week: 6,
    day: 4,
    title: 'Campaign Budgeting',
    description: 'Plan budget allocation for campaigns.',
  ),
  Roadmap(
    id: 'smm-m2-w6-d5',
    role: 'Social Media Manager',
    week: 6,
    day: 5,
    title: 'Campaign Optimization',
    description: 'Refine campaigns based on analytics and insights.',
  ),
  Roadmap(
    id: 'smm-m2-w6-d6',
    role: 'Social Media Manager',
    week: 6,
    day: 6,
    title: 'Community Engagement Strategies',
    description: 'Enhance interaction with audience and respond to comments.',
  ),
  Roadmap(
    id: 'smm-m2-w6-d7',
    role: 'Social Media Manager',
    week: 6,
    day: 7,
    title: 'Week 6 Project: Paid Ad Campaign',
    description: 'Create a small-scale paid social media ad campaign targeting a segment.',
  ),

  // Week 7
  Roadmap(
    id: 'smm-m2-w7-d1',
    role: 'Social Media Manager',
    week: 7,
    day: 1,
    title: 'Content Repurposing',
    description: 'Transform existing content into different formats for multiple platforms.',
  ),
  Roadmap(
    id: 'smm-m2-w7-d2',
    role: 'Social Media Manager',
    week: 7,
    day: 2,
    title: 'Cross-Platform Campaigns',
    description: 'Coordinate campaigns across Instagram, Twitter, TikTok, and LinkedIn.',
  ),
  Roadmap(
    id: 'smm-m2-w7-d3',
    role: 'Social Media Manager',
    week: 7,
    day: 3,
    title: 'Content Scheduling Tools',
    description: 'Advanced usage of tools like Hootsuite, Buffer, and Later.',
  ),
  Roadmap(
    id: 'smm-m2-w7-d4',
    role: 'Social Media Manager',
    week: 7,
    day: 4,
    title: 'Engagement Tracking',
    description: 'Track and measure engagement across campaigns.',
  ),
  Roadmap(
    id: 'smm-m2-w7-d5',
    role: 'Social Media Manager',
    week: 7,
    day: 5,
    title: 'Weekly Performance Review',
    description: 'Analyze performance of last week’s campaigns.',
  ),
  Roadmap(
    id: 'smm-m2-w7-d6',
    role: 'Social Media Manager',
    week: 7,
    day: 6,
    title: 'Strategy Refinement',
    description: 'Refine social media strategies for better results.',
  ),
  Roadmap(
    id: 'smm-m2-w7-d7',
    role: 'Social Media Manager',
    week: 7,
    day: 7,
    title: 'Week 7 Project: Cross-Platform Engagement',
    description: 'Plan and execute a cross-platform engagement campaign.',
  ),

  // Week 8
  Roadmap(
    id: 'smm-m2-w8-d1',
    role: 'Social Media Manager',
    week: 8,
    day: 1,
    title: 'Influencer Research',
    description: 'Identify relevant influencers for your niche.',
  ),
  Roadmap(
    id: 'smm-m2-w8-d2',
    role: 'Social Media Manager',
    week: 8,
    day: 2,
    title: 'Collaboration Outreach',
    description: 'Reach out to influencers for collaboration.',
  ),
  Roadmap(
    id: 'smm-m2-w8-d3',
    role: 'Social Media Manager',
    week: 8,
    day: 3,
    title: 'Campaign Coordination',
    description: 'Coordinate posts and promotions with influencers.',
  ),
  Roadmap(
    id: 'smm-m2-w8-d4',
    role: 'Social Media Manager',
    week: 8,
    day: 4,
    title: 'Content Optimization',
    description: 'Optimize influencer content for maximum reach.',
  ),
  Roadmap(
    id: 'smm-m2-w8-d5',
    role: 'Social Media Manager',
    week: 8,
    day: 5,
    title: 'Monitoring Engagement',
    description: 'Track performance and engagement of influencer campaigns.',
  ),
  Roadmap(
    id: 'smm-m2-w8-d6',
    role: 'Social Media Manager',
    week: 8,
    day: 6,
    title: 'Reporting & Feedback',
    description: 'Prepare a report of influencer campaign performance.',
  ),
  Roadmap(
    id: 'smm-m2-w8-d7',
    role: 'Social Media Manager',
    week: 8,
    day: 7,
    title: 'Week 8 Project: Influencer Collaboration Campaign',
    description: 'Plan and execute a full influencer collaboration campaign with measurable engagement goals.',
  ),
  // -------------------------
  // Month 3
  // -------------------------

  // Week 9
  Roadmap(
    id: 'smm-m3-w9-d1',
    role: 'Social Media Manager',
    week: 9,
    day: 1,
    title: 'Crisis Management Planning',
    description: 'Learn to handle negative feedback and social media crises.',
  ),
  Roadmap(
    id: 'smm-m3-w9-d2',
    role: 'Social Media Manager',
    week: 9,
    day: 2,
    title: 'Advanced Analytics',
    description: 'Deep dive into engagement and conversion analytics.',
  ),
  Roadmap(
    id: 'smm-m3-w9-d3',
    role: 'Social Media Manager',
    week: 9,
    day: 3,
    title: 'Competitor Analysis',
    description: 'Analyze competitor campaigns and strategies.',
  ),
  Roadmap(
    id: 'smm-m3-w9-d4',
    role: 'Social Media Manager',
    week: 9,
    day: 4,
    title: 'Trendspotting',
    description: 'Identify current trends and viral content opportunities.',
  ),
  Roadmap(
    id: 'smm-m3-w9-d5',
    role: 'Social Media Manager',
    week: 9,
    day: 5,
    title: 'Automation Tools',
    description: 'Set up automation for posts and reporting.',
  ),
  Roadmap(
    id: 'smm-m3-w9-d6',
    role: 'Social Media Manager',
    week: 9,
    day: 6,
    title: 'Team Collaboration',
    description: 'Coordinate social media tasks with the team.',
  ),
  Roadmap(
    id: 'smm-m3-w9-d7',
    role: 'Social Media Manager',
    week: 9,
    day: 7,
    title: 'Week 9 Project: Crisis Simulation Campaign',
    description: 'Create a mock crisis scenario and plan a full social media response.',
  ),

  // Week 10
  Roadmap(
    id: 'smm-m3-w10-d1',
    role: 'Social Media Manager',
    week: 10,
    day: 1,
    title: 'User-Generated Content Strategy',
    description: 'Encourage audience-generated content to boost engagement.',
  ),
  Roadmap(
    id: 'smm-m3-w10-d2',
    role: 'Social Media Manager',
    week: 10,
    day: 2,
    title: 'Campaign Personalization',
    description: 'Tailor content to segmented audience groups.',
  ),
  Roadmap(
    id: 'smm-m3-w10-d3',
    role: 'Social Media Manager',
    week: 10,
    day: 3,
    title: 'Content Repurposing Advanced',
    description: 'Repurpose content efficiently across multiple channels.',
  ),
  Roadmap(
    id: 'smm-m3-w10-d4',
    role: 'Social Media Manager',
    week: 10,
    day: 4,
    title: 'A/B Testing',
    description: 'Test variations of posts to optimize performance.',
  ),
  Roadmap(
    id: 'smm-m3-w10-d5',
    role: 'Social Media Manager',
    week: 10,
    day: 5,
    title: 'Advanced Scheduling',
    description: 'Use analytics to optimize post timing.',
  ),
  Roadmap(
    id: 'smm-m3-w10-d6',
    role: 'Social Media Manager',
    week: 10,
    day: 6,
    title: 'Content Quality Audit',
    description: 'Evaluate and improve content quality.',
  ),
  Roadmap(
    id: 'smm-m3-w10-d7',
    role: 'Social Media Manager',
    week: 10,
    day: 7,
    title: 'Week 10 Project: A/B Tested Campaign',
    description: 'Run an A/B tested social media campaign and report results.',
  ),

  // Week 11
  Roadmap(
    id: 'smm-m3-w11-d1',
    role: 'Social Media Manager',
    week: 11,
    day: 1,
    title: 'Engagement Analytics Reporting',
    description: 'Prepare detailed engagement reports for stakeholders.',
  ),
  Roadmap(
    id: 'smm-m3-w11-d2',
    role: 'Social Media Manager',
    week: 11,
    day: 2,
    title: 'Content Gap Analysis',
    description: 'Identify content gaps in campaigns and plan improvements.',
  ),
  Roadmap(
    id: 'smm-m3-w11-d3',
    role: 'Social Media Manager',
    week: 11,
    day: 3,
    title: 'Collaborative Campaigns',
    description: 'Work with other departments for cross-promotion.',
  ),
  Roadmap(
    id: 'smm-m3-w11-d4',
    role: 'Social Media Manager',
    week: 11,
    day: 4,
    title: 'Advanced Storytelling',
    description: 'Craft stories that increase brand affinity and engagement.',
  ),
  Roadmap(
    id: 'smm-m3-w11-d5',
    role: 'Social Media Manager',
    week: 11,
    day: 5,
    title: 'Optimization for Conversions',
    description: 'Adjust campaigns to maximize leads or sales.',
  ),
  Roadmap(
    id: 'smm-m3-w11-d6',
    role: 'Social Media Manager',
    week: 11,
    day: 6,
    title: 'Final Campaign Review',
    description: 'Prepare final reviews of all ongoing campaigns.',
  ),
  Roadmap(
    id: 'smm-m3-w11-d7',
    role: 'Social Media Manager',
    week: 11,
    day: 7,
    title: 'Week 11 Project: Collaborative Campaign Execution',
    description: 'Execute a collaborative cross-platform campaign with measurable KPIs.',
  ),

  // Week 12
  Roadmap(
    id: 'smm-m3-w12-d1',
    role: 'Social Media Manager',
    week: 12,
    day: 1,
    title: 'Brand Awareness Strategies',
    description: 'Develop strategies to increase brand visibility.',
  ),
  Roadmap(
    id: 'smm-m3-w12-d2',
    role: 'Social Media Manager',
    week: 12,
    day: 2,
    title: 'Content Finalization',
    description: 'Finalize content for high-impact campaigns.',
  ),
  Roadmap(
    id: 'smm-m3-w12-d3',
    role: 'Social Media Manager',
    week: 12,
    day: 3,
    title: 'Campaign Execution',
    description: 'Launch the finalized campaigns on all platforms.',
  ),
  Roadmap(
    id: 'smm-m3-w12-d4',
    role: 'Social Media Manager',
    week: 12,
    day: 4,
    title: 'Performance Monitoring',
    description: 'Monitor campaign KPIs in real-time.',
  ),
  Roadmap(
    id: 'smm-m3-w12-d5',
    role: 'Social Media Manager',
    week: 12,
    day: 5,
    title: 'Feedback Collection',
    description: 'Gather feedback from audience and stakeholders.',
  ),
  Roadmap(
    id: 'smm-m3-w12-d6',
    role: 'Social Media Manager',
    week: 12,
    day: 6,
    title: 'Report Preparation',
    description: 'Prepare comprehensive campaign reports.',
  ),
  Roadmap(
    id: 'smm-m3-w12-d7',
    role: 'Social Media Manager',
    week: 12,
    day: 7,
    title: 'Week 12 Project: Final Capstone Campaign',
    description: 'Execute a full-scale capstone campaign and deliver final performance report.',
  ),
];