// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3GQsgOAssn2UG9tKLTR27W8NIhPNJUWs',
    appId: '1:1023291833256:web:837434d109812b09fa3b9d',
    messagingSenderId: '1023291833256',
    projectId: 'tech-mafias',
    authDomain: 'tech-mafias.firebaseapp.com',
    storageBucket: 'tech-mafias.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK70pNg9NixE-LlM0XpDm1plCj2kBkdio',
    appId: '1:1023291833256:android:6a5bf5b3a5db9a6afa3b9d',
    messagingSenderId: '1023291833256',
    projectId: 'tech-mafias',
    storageBucket: 'tech-mafias.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1brKPRSieuOf1d1QT9qQ3zycas2aqwoA',
    appId: '1:1023291833256:ios:eecede83d664e63cfa3b9d',
    messagingSenderId: '1023291833256',
    projectId: 'tech-mafias',
    storageBucket: 'tech-mafias.firebasestorage.app',
    iosBundleId: 'com.example.techmafias',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1brKPRSieuOf1d1QT9qQ3zycas2aqwoA',
    appId: '1:1023291833256:ios:eecede83d664e63cfa3b9d',
    messagingSenderId: '1023291833256',
    projectId: 'tech-mafias',
    storageBucket: 'tech-mafias.firebasestorage.app',
    iosBundleId: 'com.example.techmafias',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3GQsgOAssn2UG9tKLTR27W8NIhPNJUWs',
    appId: '1:1023291833256:web:5ed78cae3f28060bfa3b9d',
    messagingSenderId: '1023291833256',
    projectId: 'tech-mafias',
    authDomain: 'tech-mafias.firebaseapp.com',
    storageBucket: 'tech-mafias.firebasestorage.app',
  );
}
